//Auto-generated by /home/vagrant/.gem/ruby/2.7.0/gems/rock-qtbindings-4.8.6.5/ext/build/generator/bin/smokegen. DO NOT EDIT.
#include <qtcore_includes.h>
#include <typeinfo>

#include <smoke.h>
#include <qtcore_smoke.h>

class __internal_SmokeClass {};

namespace __smokeqtcore {

class x_QUuid : public QUuid {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    static void x_1(Smoke::Stack x) {
        // QUuid* QUuid()
        x_QUuid* xret = new x_QUuid();
        x[0].s_class = (void*)xret;
    }
    explicit x_QUuid() : QUuid() {}
    static void x_2(Smoke::Stack x) {
        // QUuid* QUuid(unsigned int, unsigned short, unsigned short, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
        x_QUuid* xret = new x_QUuid((unsigned int)x[1].s_uint,(unsigned short)x[2].s_ushort,(unsigned short)x[3].s_ushort,(unsigned char)x[4].s_uchar,(unsigned char)x[5].s_uchar,(unsigned char)x[6].s_uchar,(unsigned char)x[7].s_uchar,(unsigned char)x[8].s_uchar,(unsigned char)x[9].s_uchar,(unsigned char)x[10].s_uchar,(unsigned char)x[11].s_uchar);
        x[0].s_class = (void*)xret;
    }
    explicit x_QUuid(unsigned int x1, unsigned short x2, unsigned short x3, unsigned char x4, unsigned char x5, unsigned char x6, unsigned char x7, unsigned char x8, unsigned char x9, unsigned char x10, unsigned char x11) : QUuid(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11) {}
    static void x_3(Smoke::Stack x) {
        // QUuid* QUuid(const QString&)
        x_QUuid* xret = new x_QUuid(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QUuid(const QString& x1) : QUuid(x1) {}
    static void x_4(Smoke::Stack x) {
        // QUuid* QUuid(const char*)
        x_QUuid* xret = new x_QUuid((const char*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QUuid(const char* x1) : QUuid(x1) {}
    void x_5(Smoke::Stack x) {
        // QString toString() const
        QString xret = ((const x_QUuid*)this)->QUuid::toString();
        x[0].s_class = (void*)new QString(xret);
    }
    void x_6(Smoke::Stack x) {
        // QString operator QString() const
        QString xret = ((const x_QUuid*)this)->QUuid::operator QString();
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_7(Smoke::Stack x) {
        // QUuid* QUuid(const QByteArray&)
        x_QUuid* xret = new x_QUuid(*(const QByteArray*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QUuid(const QByteArray& x1) : QUuid(x1) {}
    void x_8(Smoke::Stack x) {
        // QByteArray toByteArray() const
        QByteArray xret = ((const x_QUuid*)this)->QUuid::toByteArray();
        x[0].s_class = (void*)new QByteArray(xret);
    }
    void x_9(Smoke::Stack x) {
        // QByteArray toRfc4122() const
        QByteArray xret = ((const x_QUuid*)this)->QUuid::toRfc4122();
        x[0].s_class = (void*)new QByteArray(xret);
    }
    static void x_10(Smoke::Stack x) {
        // static QUuid fromRfc4122(const QByteArray&)
        QUuid xret = QUuid::fromRfc4122(*(const QByteArray*)x[1].s_class);
        x[0].s_class = (void*)new QUuid(xret);
    }
    void x_11(Smoke::Stack x) {
        // bool isNull() const
        bool xret = ((const x_QUuid*)this)->QUuid::isNull();
        x[0].s_bool = xret;
    }
    void x_12(Smoke::Stack x) {
        // bool operator==(const QUuid&) const
        bool xret = ((const x_QUuid*)this)->QUuid::operator==(*(const QUuid*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_13(Smoke::Stack x) {
        // bool operator!=(const QUuid&) const
        bool xret = ((const x_QUuid*)this)->QUuid::operator!=(*(const QUuid*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_14(Smoke::Stack x) {
        // bool operator<(const QUuid&) const
        bool xret = ((const x_QUuid*)this)->QUuid::operator<(*(const QUuid*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_15(Smoke::Stack x) {
        // bool operator>(const QUuid&) const
        bool xret = ((const x_QUuid*)this)->QUuid::operator>(*(const QUuid*)x[1].s_class);
        x[0].s_bool = xret;
    }
    static void x_16(Smoke::Stack x) {
        // static QUuid createUuid()
        QUuid xret = QUuid::createUuid();
        x[0].s_class = (void*)new QUuid(xret);
    }
    void x_17(Smoke::Stack x) {
        // QUuid::Variant variant() const
        QUuid::Variant xret = ((const x_QUuid*)this)->QUuid::variant();
        x[0].s_enum = xret;
    }
    void x_18(Smoke::Stack x) {
        // QUuid::Version version() const
        QUuid::Version xret = ((const x_QUuid*)this)->QUuid::version();
        x[0].s_enum = xret;
    }
    static void x_19(Smoke::Stack x) {
        // QUuid* QUuid(const QUuid&)
        x_QUuid* xret = new x_QUuid(*(const QUuid*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QUuid(const QUuid& x1) : QUuid(x1) {}
    static void x_20(Smoke::Stack x) {
        x[0].s_enum = (long)QUuid::VarUnknown;
    }
    static void x_21(Smoke::Stack x) {
        x[0].s_enum = (long)QUuid::NCS;
    }
    static void x_22(Smoke::Stack x) {
        x[0].s_enum = (long)QUuid::DCE;
    }
    static void x_23(Smoke::Stack x) {
        x[0].s_enum = (long)QUuid::Microsoft;
    }
    static void x_24(Smoke::Stack x) {
        x[0].s_enum = (long)QUuid::Reserved;
    }
    static void x_25(Smoke::Stack x) {
        x[0].s_enum = (long)QUuid::VerUnknown;
    }
    static void x_26(Smoke::Stack x) {
        x[0].s_enum = (long)QUuid::Time;
    }
    static void x_27(Smoke::Stack x) {
        x[0].s_enum = (long)QUuid::EmbeddedPOSIX;
    }
    static void x_28(Smoke::Stack x) {
        x[0].s_enum = (long)QUuid::Name;
    }
    static void x_29(Smoke::Stack x) {
        x[0].s_enum = (long)QUuid::Random;
    }
    static void xenum_operation(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
        switch(xtype) {
        case 369: //QUuid::Variant
            switch(xop) {
                case Smoke::EnumNew:
                    xdata = (void*)new QUuid::Variant;
                    break;
                case Smoke::EnumDelete:
                    delete (QUuid::Variant*)xdata;
                    break;
                case Smoke::EnumFromLong:
                    *(QUuid::Variant*)xdata = (QUuid::Variant)xvalue;
                    break;
                case Smoke::EnumToLong:
                    xvalue = (long)*(QUuid::Variant*)xdata;
                    break;
            }
            break;
        case 370: //QUuid::Version
            switch(xop) {
                case Smoke::EnumNew:
                    xdata = (void*)new QUuid::Version;
                    break;
                case Smoke::EnumDelete:
                    delete (QUuid::Version*)xdata;
                    break;
                case Smoke::EnumFromLong:
                    *(QUuid::Version*)xdata = (QUuid::Version)xvalue;
                    break;
                case Smoke::EnumToLong:
                    xvalue = (long)*(QUuid::Version*)xdata;
                    break;
            }
            break;
        }
    }
    ~x_QUuid() { this->_binding->deleted(136, (void*)this); }
};
void xenum_QUuid(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
    x_QUuid::xenum_operation(xop, xtype, xdata, xvalue);
}
void xcall_QUuid(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QUuid *xself = (x_QUuid*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: x_QUuid::x_1(args);	break;
        case 2: x_QUuid::x_2(args);	break;
        case 3: x_QUuid::x_3(args);	break;
        case 4: x_QUuid::x_4(args);	break;
        case 5: xself->x_5(args);	break;
        case 6: xself->x_6(args);	break;
        case 7: x_QUuid::x_7(args);	break;
        case 8: xself->x_8(args);	break;
        case 9: xself->x_9(args);	break;
        case 10: x_QUuid::x_10(args);	break;
        case 11: xself->x_11(args);	break;
        case 12: xself->x_12(args);	break;
        case 13: xself->x_13(args);	break;
        case 14: xself->x_14(args);	break;
        case 15: xself->x_15(args);	break;
        case 16: x_QUuid::x_16(args);	break;
        case 17: xself->x_17(args);	break;
        case 18: xself->x_18(args);	break;
        case 19: x_QUuid::x_19(args);	break;
        case 20: x_QUuid::x_20(args);	break;
        case 21: x_QUuid::x_21(args);	break;
        case 22: x_QUuid::x_22(args);	break;
        case 23: x_QUuid::x_23(args);	break;
        case 24: x_QUuid::x_24(args);	break;
        case 25: x_QUuid::x_25(args);	break;
        case 26: x_QUuid::x_26(args);	break;
        case 27: x_QUuid::x_27(args);	break;
        case 28: x_QUuid::x_28(args);	break;
        case 29: x_QUuid::x_29(args);	break;
        case 30: delete (QUuid*)xself;	break;
    }
}
class x_QVariant : public QVariant {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    static void x_1(Smoke::Stack x) {
        // QVariant* QVariant()
        x_QVariant* xret = new x_QVariant();
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant() : QVariant() {}
    static void x_2(Smoke::Stack x) {
        // QVariant* QVariant(QVariant::Type)
        x_QVariant* xret = new x_QVariant((QVariant::Type)x[1].s_enum);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(QVariant::Type x1) : QVariant(x1) {}
    static void x_3(Smoke::Stack x) {
        // QVariant* QVariant(int, const void*)
        x_QVariant* xret = new x_QVariant((int)x[1].s_int,(const void*)x[2].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(int x1, const void* x2) : QVariant(x1, x2) {}
    static void x_4(Smoke::Stack x) {
        // QVariant* QVariant(int, const void*, unsigned int)
        x_QVariant* xret = new x_QVariant((int)x[1].s_int,(const void*)x[2].s_class,(unsigned int)x[3].s_uint);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(int x1, const void* x2, unsigned int x3) : QVariant(x1, x2, x3) {}
    static void x_5(Smoke::Stack x) {
        // QVariant* QVariant(const QVariant&)
        x_QVariant* xret = new x_QVariant(*(const QVariant*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QVariant& x1) : QVariant(x1) {}
    static void x_6(Smoke::Stack x) {
        // QVariant* QVariant(QDataStream&)
        x_QVariant* xret = new x_QVariant(*(QDataStream*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(QDataStream& x1) : QVariant(x1) {}
    static void x_7(Smoke::Stack x) {
        // QVariant* QVariant(int)
        x_QVariant* xret = new x_QVariant((int)x[1].s_int);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(int x1) : QVariant(x1) {}
    static void x_8(Smoke::Stack x) {
        // QVariant* QVariant(unsigned int)
        x_QVariant* xret = new x_QVariant((unsigned int)x[1].s_uint);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(unsigned int x1) : QVariant(x1) {}
    static void x_9(Smoke::Stack x) {
        // QVariant* QVariant(long long)
        x_QVariant* xret = new x_QVariant(*(long long*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(long long x1) : QVariant(x1) {}
    static void x_10(Smoke::Stack x) {
        // QVariant* QVariant(unsigned long long)
        x_QVariant* xret = new x_QVariant(*(unsigned long long*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(unsigned long long x1) : QVariant(x1) {}
    static void x_11(Smoke::Stack x) {
        // QVariant* QVariant(bool)
        x_QVariant* xret = new x_QVariant((bool)x[1].s_bool);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(bool x1) : QVariant(x1) {}
    static void x_12(Smoke::Stack x) {
        // QVariant* QVariant(double)
        x_QVariant* xret = new x_QVariant((double)x[1].s_double);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(double x1) : QVariant(x1) {}
    static void x_13(Smoke::Stack x) {
        // QVariant* QVariant(float)
        x_QVariant* xret = new x_QVariant((float)x[1].s_float);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(float x1) : QVariant(x1) {}
    static void x_14(Smoke::Stack x) {
        // QVariant* QVariant(const QByteArray&)
        x_QVariant* xret = new x_QVariant(*(const QByteArray*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QByteArray& x1) : QVariant(x1) {}
    static void x_15(Smoke::Stack x) {
        // QVariant* QVariant(const QBitArray&)
        x_QVariant* xret = new x_QVariant(*(const QBitArray*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QBitArray& x1) : QVariant(x1) {}
    static void x_16(Smoke::Stack x) {
        // QVariant* QVariant(const QString&)
        x_QVariant* xret = new x_QVariant(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QString& x1) : QVariant(x1) {}
    static void x_17(Smoke::Stack x) {
        // QVariant* QVariant(const QLatin1String&)
        x_QVariant* xret = new x_QVariant(*(const QLatin1String*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QLatin1String& x1) : QVariant(x1) {}
    static void x_18(Smoke::Stack x) {
        // QVariant* QVariant(const QStringList&)
        x_QVariant* xret = new x_QVariant(*(const QStringList*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QStringList& x1) : QVariant(x1) {}
    static void x_19(Smoke::Stack x) {
        // QVariant* QVariant(const QChar&)
        x_QVariant* xret = new x_QVariant(*(const QChar*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QChar& x1) : QVariant(x1) {}
    static void x_20(Smoke::Stack x) {
        // QVariant* QVariant(const QDate&)
        x_QVariant* xret = new x_QVariant(*(const QDate*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QDate& x1) : QVariant(x1) {}
    static void x_21(Smoke::Stack x) {
        // QVariant* QVariant(const QTime&)
        x_QVariant* xret = new x_QVariant(*(const QTime*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QTime& x1) : QVariant(x1) {}
    static void x_22(Smoke::Stack x) {
        // QVariant* QVariant(const QDateTime&)
        x_QVariant* xret = new x_QVariant(*(const QDateTime*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QDateTime& x1) : QVariant(x1) {}
    static void x_23(Smoke::Stack x) {
        // QVariant* QVariant(const QList<QVariant>&)
        x_QVariant* xret = new x_QVariant(*(const QList<QVariant>*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QList<QVariant>& x1) : QVariant(x1) {}
    static void x_24(Smoke::Stack x) {
        // QVariant* QVariant(const QMap<QString,QVariant>&)
        x_QVariant* xret = new x_QVariant(*(const QMap<QString,QVariant>*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QMap<QString,QVariant>& x1) : QVariant(x1) {}
    static void x_25(Smoke::Stack x) {
        // QVariant* QVariant(const QHash<QString,QVariant>&)
        x_QVariant* xret = new x_QVariant(*(const QHash<QString,QVariant>*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QHash<QString,QVariant>& x1) : QVariant(x1) {}
    static void x_26(Smoke::Stack x) {
        // QVariant* QVariant(const QSize&)
        x_QVariant* xret = new x_QVariant(*(const QSize*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QSize& x1) : QVariant(x1) {}
    static void x_27(Smoke::Stack x) {
        // QVariant* QVariant(const QSizeF&)
        x_QVariant* xret = new x_QVariant(*(const QSizeF*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QSizeF& x1) : QVariant(x1) {}
    static void x_28(Smoke::Stack x) {
        // QVariant* QVariant(const QPoint&)
        x_QVariant* xret = new x_QVariant(*(const QPoint*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QPoint& x1) : QVariant(x1) {}
    static void x_29(Smoke::Stack x) {
        // QVariant* QVariant(const QPointF&)
        x_QVariant* xret = new x_QVariant(*(const QPointF*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QPointF& x1) : QVariant(x1) {}
    static void x_30(Smoke::Stack x) {
        // QVariant* QVariant(const QLine&)
        x_QVariant* xret = new x_QVariant(*(const QLine*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QLine& x1) : QVariant(x1) {}
    static void x_31(Smoke::Stack x) {
        // QVariant* QVariant(const QLineF&)
        x_QVariant* xret = new x_QVariant(*(const QLineF*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QLineF& x1) : QVariant(x1) {}
    static void x_32(Smoke::Stack x) {
        // QVariant* QVariant(const QRect&)
        x_QVariant* xret = new x_QVariant(*(const QRect*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QRect& x1) : QVariant(x1) {}
    static void x_33(Smoke::Stack x) {
        // QVariant* QVariant(const QRectF&)
        x_QVariant* xret = new x_QVariant(*(const QRectF*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QRectF& x1) : QVariant(x1) {}
    static void x_34(Smoke::Stack x) {
        // QVariant* QVariant(const QUrl&)
        x_QVariant* xret = new x_QVariant(*(const QUrl*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QUrl& x1) : QVariant(x1) {}
    static void x_35(Smoke::Stack x) {
        // QVariant* QVariant(const QLocale&)
        x_QVariant* xret = new x_QVariant(*(const QLocale*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QLocale& x1) : QVariant(x1) {}
    static void x_36(Smoke::Stack x) {
        // QVariant* QVariant(const QRegExp&)
        x_QVariant* xret = new x_QVariant(*(const QRegExp*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QRegExp& x1) : QVariant(x1) {}
    static void x_37(Smoke::Stack x) {
        // QVariant* QVariant(const QEasingCurve&)
        x_QVariant* xret = new x_QVariant(*(const QEasingCurve*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(const QEasingCurve& x1) : QVariant(x1) {}
    static void x_38(Smoke::Stack x) {
        // QVariant* QVariant(Qt::GlobalColor)
        x_QVariant* xret = new x_QVariant((Qt::GlobalColor)x[1].s_enum);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariant(Qt::GlobalColor x1) : QVariant(x1) {}
    void x_39(Smoke::Stack x) {
        // QVariant& operator=(const QVariant&)
        QVariant& xret = this->QVariant::operator=(*(const QVariant*)x[1].s_class);
        x[0].s_class = (void*)&xret;
    }
    void x_40(Smoke::Stack x) {
        // void swap(QVariant&)
        this->QVariant::swap(*(QVariant*)x[1].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_41(Smoke::Stack x) {
        // QVariant::Type type() const
        QVariant::Type xret = ((const x_QVariant*)this)->QVariant::type();
        x[0].s_enum = xret;
    }
    void x_42(Smoke::Stack x) {
        // int userType() const
        int xret = ((const x_QVariant*)this)->QVariant::userType();
        x[0].s_int = xret;
    }
    void x_43(Smoke::Stack x) {
        // const char* typeName() const
        const char* xret = ((const x_QVariant*)this)->QVariant::typeName();
        x[0].s_class = (void*)xret;
    }
    void x_44(Smoke::Stack x) {
        // bool canConvert(QVariant::Type) const
        bool xret = ((const x_QVariant*)this)->QVariant::canConvert((QVariant::Type)x[1].s_enum);
        x[0].s_bool = xret;
    }
    void x_45(Smoke::Stack x) {
        // bool convert(QVariant::Type)
        bool xret = this->QVariant::convert((QVariant::Type)x[1].s_enum);
        x[0].s_bool = xret;
    }
    void x_46(Smoke::Stack x) {
        // bool isValid() const
        bool xret = ((const x_QVariant*)this)->QVariant::isValid();
        x[0].s_bool = xret;
    }
    void x_47(Smoke::Stack x) {
        // bool isNull() const
        bool xret = ((const x_QVariant*)this)->QVariant::isNull();
        x[0].s_bool = xret;
    }
    void x_48(Smoke::Stack x) {
        // void clear()
        this->QVariant::clear();
        (void)x; // noop (for compiler warning)
    }
    void x_49(Smoke::Stack x) {
        // void detach()
        this->QVariant::detach();
        (void)x; // noop (for compiler warning)
    }
    void x_50(Smoke::Stack x) {
        // bool isDetached() const
        bool xret = ((const x_QVariant*)this)->QVariant::isDetached();
        x[0].s_bool = xret;
    }
    void x_51(Smoke::Stack x) {
        // int toInt(bool*) const
        int xret = ((const x_QVariant*)this)->QVariant::toInt((bool*)x[1].s_class);
        x[0].s_int = xret;
    }
    void x_52(Smoke::Stack x) {
        // unsigned int toUInt(bool*) const
        unsigned int xret = ((const x_QVariant*)this)->QVariant::toUInt((bool*)x[1].s_class);
        x[0].s_uint = xret;
    }
    void x_53(Smoke::Stack x) {
        // long long toLongLong(bool*) const
        long long xret = ((const x_QVariant*)this)->QVariant::toLongLong((bool*)x[1].s_class);
        x[0].s_class = (void*)new long long(xret);
    }
    void x_54(Smoke::Stack x) {
        // unsigned long long toULongLong(bool*) const
        unsigned long long xret = ((const x_QVariant*)this)->QVariant::toULongLong((bool*)x[1].s_class);
        x[0].s_class = (void*)new unsigned long long(xret);
    }
    void x_55(Smoke::Stack x) {
        // bool toBool() const
        bool xret = ((const x_QVariant*)this)->QVariant::toBool();
        x[0].s_bool = xret;
    }
    void x_56(Smoke::Stack x) {
        // double toDouble(bool*) const
        double xret = ((const x_QVariant*)this)->QVariant::toDouble((bool*)x[1].s_class);
        x[0].s_double = xret;
    }
    void x_57(Smoke::Stack x) {
        // float toFloat(bool*) const
        float xret = ((const x_QVariant*)this)->QVariant::toFloat((bool*)x[1].s_class);
        x[0].s_float = xret;
    }
    void x_58(Smoke::Stack x) {
        // double toReal(bool*) const
        double xret = ((const x_QVariant*)this)->QVariant::toReal((bool*)x[1].s_class);
        x[0].s_double = xret;
    }
    void x_59(Smoke::Stack x) {
        // QByteArray toByteArray() const
        QByteArray xret = ((const x_QVariant*)this)->QVariant::toByteArray();
        x[0].s_class = (void*)new QByteArray(xret);
    }
    void x_60(Smoke::Stack x) {
        // QBitArray toBitArray() const
        QBitArray xret = ((const x_QVariant*)this)->QVariant::toBitArray();
        x[0].s_class = (void*)new QBitArray(xret);
    }
    void x_61(Smoke::Stack x) {
        // QString toString() const
        QString xret = ((const x_QVariant*)this)->QVariant::toString();
        x[0].s_class = (void*)new QString(xret);
    }
    void x_62(Smoke::Stack x) {
        // QStringList toStringList() const
        QStringList xret = ((const x_QVariant*)this)->QVariant::toStringList();
        x[0].s_class = (void*)new QStringList(xret);
    }
    void x_63(Smoke::Stack x) {
        // QChar toChar() const
        QChar xret = ((const x_QVariant*)this)->QVariant::toChar();
        x[0].s_class = (void*)new QChar(xret);
    }
    void x_64(Smoke::Stack x) {
        // QDate toDate() const
        QDate xret = ((const x_QVariant*)this)->QVariant::toDate();
        x[0].s_class = (void*)new QDate(xret);
    }
    void x_65(Smoke::Stack x) {
        // QTime toTime() const
        QTime xret = ((const x_QVariant*)this)->QVariant::toTime();
        x[0].s_class = (void*)new QTime(xret);
    }
    void x_66(Smoke::Stack x) {
        // QDateTime toDateTime() const
        QDateTime xret = ((const x_QVariant*)this)->QVariant::toDateTime();
        x[0].s_class = (void*)new QDateTime(xret);
    }
    void x_67(Smoke::Stack x) {
        // QList<QVariant> toList() const
        QList<QVariant> xret = ((const x_QVariant*)this)->QVariant::toList();
        x[0].s_class = (void*)new QList<QVariant>(xret);
    }
    void x_68(Smoke::Stack x) {
        // QMap<QString,QVariant> toMap() const
        QMap<QString,QVariant> xret = ((const x_QVariant*)this)->QVariant::toMap();
        x[0].s_class = (void*)new QMap<QString,QVariant>(xret);
    }
    void x_69(Smoke::Stack x) {
        // QHash<QString,QVariant> toHash() const
        QHash<QString,QVariant> xret = ((const x_QVariant*)this)->QVariant::toHash();
        x[0].s_class = (void*)new QHash<QString,QVariant>(xret);
    }
    void x_70(Smoke::Stack x) {
        // QPoint toPoint() const
        QPoint xret = ((const x_QVariant*)this)->QVariant::toPoint();
        x[0].s_class = (void*)new QPoint(xret);
    }
    void x_71(Smoke::Stack x) {
        // QPointF toPointF() const
        QPointF xret = ((const x_QVariant*)this)->QVariant::toPointF();
        x[0].s_class = (void*)new QPointF(xret);
    }
    void x_72(Smoke::Stack x) {
        // QRect toRect() const
        QRect xret = ((const x_QVariant*)this)->QVariant::toRect();
        x[0].s_class = (void*)new QRect(xret);
    }
    void x_73(Smoke::Stack x) {
        // QSize toSize() const
        QSize xret = ((const x_QVariant*)this)->QVariant::toSize();
        x[0].s_class = (void*)new QSize(xret);
    }
    void x_74(Smoke::Stack x) {
        // QSizeF toSizeF() const
        QSizeF xret = ((const x_QVariant*)this)->QVariant::toSizeF();
        x[0].s_class = (void*)new QSizeF(xret);
    }
    void x_75(Smoke::Stack x) {
        // QLine toLine() const
        QLine xret = ((const x_QVariant*)this)->QVariant::toLine();
        x[0].s_class = (void*)new QLine(xret);
    }
    void x_76(Smoke::Stack x) {
        // QLineF toLineF() const
        QLineF xret = ((const x_QVariant*)this)->QVariant::toLineF();
        x[0].s_class = (void*)new QLineF(xret);
    }
    void x_77(Smoke::Stack x) {
        // QRectF toRectF() const
        QRectF xret = ((const x_QVariant*)this)->QVariant::toRectF();
        x[0].s_class = (void*)new QRectF(xret);
    }
    void x_78(Smoke::Stack x) {
        // QUrl toUrl() const
        QUrl xret = ((const x_QVariant*)this)->QVariant::toUrl();
        x[0].s_class = (void*)new QUrl(xret);
    }
    void x_79(Smoke::Stack x) {
        // QLocale toLocale() const
        QLocale xret = ((const x_QVariant*)this)->QVariant::toLocale();
        x[0].s_class = (void*)new QLocale(xret);
    }
    void x_80(Smoke::Stack x) {
        // QRegExp toRegExp() const
        QRegExp xret = ((const x_QVariant*)this)->QVariant::toRegExp();
        x[0].s_class = (void*)new QRegExp(xret);
    }
    void x_81(Smoke::Stack x) {
        // QEasingCurve toEasingCurve() const
        QEasingCurve xret = ((const x_QVariant*)this)->QVariant::toEasingCurve();
        x[0].s_class = (void*)new QEasingCurve(xret);
    }
    void x_82(Smoke::Stack x) {
        // void load(QDataStream&)
        this->QVariant::load(*(QDataStream*)x[1].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_83(Smoke::Stack x) {
        // void save(QDataStream&) const
        ((const x_QVariant*)this)->QVariant::save(*(QDataStream*)x[1].s_class);
        (void)x; // noop (for compiler warning)
    }
    static void x_84(Smoke::Stack x) {
        // static const char* typeToName(QVariant::Type)
        const char* xret = QVariant::typeToName((QVariant::Type)x[1].s_enum);
        x[0].s_class = (void*)xret;
    }
    static void x_85(Smoke::Stack x) {
        // static QVariant::Type nameToType(const char*)
        QVariant::Type xret = QVariant::nameToType((const char*)x[1].s_class);
        x[0].s_enum = xret;
    }
    void x_86(Smoke::Stack x) {
        // void* data()
        void* xret = this->QVariant::data();
        x[0].s_class = (void*)xret;
    }
    void x_87(Smoke::Stack x) {
        // const void* constData() const
        const void* xret = ((const x_QVariant*)this)->QVariant::constData();
        x[0].s_class = (void*)xret;
    }
    void x_88(Smoke::Stack x) {
        // const void* data() const
        const void* xret = ((const x_QVariant*)this)->QVariant::data();
        x[0].s_class = (void*)xret;
    }
    void x_89(Smoke::Stack x) {
        // bool operator==(const QVariant&) const
        bool xret = ((const x_QVariant*)this)->QVariant::operator==(*(const QVariant*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_90(Smoke::Stack x) {
        // bool operator!=(const QVariant&) const
        bool xret = ((const x_QVariant*)this)->QVariant::operator!=(*(const QVariant*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_91(Smoke::Stack x) {
        // void create(int, const void*)
        this->QVariant::create((int)x[1].s_int,(const void*)x[2].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_92(Smoke::Stack x) {
        // bool cmp(const QVariant&) const
        bool xret = ((const x_QVariant*)this)->QVariant::cmp(*(const QVariant*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_93(Smoke::Stack x) {
        // QVariant::Private& data_ptr()
        QVariant::Private& xret = this->QVariant::data_ptr();
        x[0].s_class = (void*)&xret;
    }
    void x_94(Smoke::Stack x) {
        // int toInt() const
        int xret = ((const x_QVariant*)this)->QVariant::toInt((bool*)0);
        x[0].s_int = xret;
    }
    void x_95(Smoke::Stack x) {
        // unsigned int toUInt() const
        unsigned int xret = ((const x_QVariant*)this)->QVariant::toUInt((bool*)0);
        x[0].s_uint = xret;
    }
    void x_96(Smoke::Stack x) {
        // long long toLongLong() const
        long long xret = ((const x_QVariant*)this)->QVariant::toLongLong((bool*)0);
        x[0].s_class = (void*)new long long(xret);
    }
    void x_97(Smoke::Stack x) {
        // unsigned long long toULongLong() const
        unsigned long long xret = ((const x_QVariant*)this)->QVariant::toULongLong((bool*)0);
        x[0].s_class = (void*)new unsigned long long(xret);
    }
    void x_98(Smoke::Stack x) {
        // double toDouble() const
        double xret = ((const x_QVariant*)this)->QVariant::toDouble((bool*)0);
        x[0].s_double = xret;
    }
    void x_99(Smoke::Stack x) {
        // float toFloat() const
        float xret = ((const x_QVariant*)this)->QVariant::toFloat((bool*)0);
        x[0].s_float = xret;
    }
    void x_100(Smoke::Stack x) {
        // double toReal() const
        double xret = ((const x_QVariant*)this)->QVariant::toReal((bool*)0);
        x[0].s_double = xret;
    }
    void x_101(Smoke::Stack x) {
        // QVariant::Private d
        x[0].s_class = (void*)&this->QVariant::d;
    }
    void x_102(Smoke::Stack x) {
        // QVariant::Private d=
        this->QVariant::d = *(const QVariant::Private*)x[1].s_class;
    }
    static void x_103(Smoke::Stack x) {
        // static const QVariant::Handler* handler
        x[0].s_class = (void*)QVariant::handler;
    }
    static void x_104(Smoke::Stack x) {
        // static const QVariant::Handler* handler=
        QVariant::handler = (const QVariant::Handler*)x[1].s_class;
    }
    static void x_105(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Invalid;
    }
    static void x_106(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Bool;
    }
    static void x_107(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Int;
    }
    static void x_108(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::UInt;
    }
    static void x_109(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::LongLong;
    }
    static void x_110(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::ULongLong;
    }
    static void x_111(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Double;
    }
    static void x_112(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Char;
    }
    static void x_113(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Map;
    }
    static void x_114(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::List;
    }
    static void x_115(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::String;
    }
    static void x_116(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::StringList;
    }
    static void x_117(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::ByteArray;
    }
    static void x_118(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::BitArray;
    }
    static void x_119(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Date;
    }
    static void x_120(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Time;
    }
    static void x_121(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::DateTime;
    }
    static void x_122(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Url;
    }
    static void x_123(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Locale;
    }
    static void x_124(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Rect;
    }
    static void x_125(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::RectF;
    }
    static void x_126(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Size;
    }
    static void x_127(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::SizeF;
    }
    static void x_128(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Line;
    }
    static void x_129(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::LineF;
    }
    static void x_130(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Point;
    }
    static void x_131(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::PointF;
    }
    static void x_132(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::RegExp;
    }
    static void x_133(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Hash;
    }
    static void x_134(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::EasingCurve;
    }
    static void x_135(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::LastCoreType;
    }
    static void x_136(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Font;
    }
    static void x_137(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Pixmap;
    }
    static void x_138(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Brush;
    }
    static void x_139(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Color;
    }
    static void x_140(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Palette;
    }
    static void x_141(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Icon;
    }
    static void x_142(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Image;
    }
    static void x_143(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Polygon;
    }
    static void x_144(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Region;
    }
    static void x_145(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Bitmap;
    }
    static void x_146(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Cursor;
    }
    static void x_147(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::SizePolicy;
    }
    static void x_148(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::KeySequence;
    }
    static void x_149(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Pen;
    }
    static void x_150(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::TextLength;
    }
    static void x_151(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::TextFormat;
    }
    static void x_152(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Matrix;
    }
    static void x_153(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Transform;
    }
    static void x_154(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Matrix4x4;
    }
    static void x_155(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Vector2D;
    }
    static void x_156(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Vector3D;
    }
    static void x_157(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Vector4D;
    }
    static void x_158(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::Quaternion;
    }
    static void x_159(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::LastGuiType;
    }
    static void x_160(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::UserType;
    }
    static void x_161(Smoke::Stack x) {
        x[0].s_enum = (long)QVariant::LastType;
    }
    static void xenum_operation(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
        switch(xtype) {
        case 375: //QVariant::Type
            switch(xop) {
                case Smoke::EnumNew:
                    xdata = (void*)new QVariant::Type;
                    break;
                case Smoke::EnumDelete:
                    delete (QVariant::Type*)xdata;
                    break;
                case Smoke::EnumFromLong:
                    *(QVariant::Type*)xdata = (QVariant::Type)xvalue;
                    break;
                case Smoke::EnumToLong:
                    xvalue = (long)*(QVariant::Type*)xdata;
                    break;
            }
            break;
        }
    }
    ~x_QVariant() { this->_binding->deleted(137, (void*)this); }
};
void xenum_QVariant(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
    x_QVariant::xenum_operation(xop, xtype, xdata, xvalue);
}
void xcall_QVariant(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QVariant *xself = (x_QVariant*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: x_QVariant::x_1(args);	break;
        case 2: x_QVariant::x_2(args);	break;
        case 3: x_QVariant::x_3(args);	break;
        case 4: x_QVariant::x_4(args);	break;
        case 5: x_QVariant::x_5(args);	break;
        case 6: x_QVariant::x_6(args);	break;
        case 7: x_QVariant::x_7(args);	break;
        case 8: x_QVariant::x_8(args);	break;
        case 9: x_QVariant::x_9(args);	break;
        case 10: x_QVariant::x_10(args);	break;
        case 11: x_QVariant::x_11(args);	break;
        case 12: x_QVariant::x_12(args);	break;
        case 13: x_QVariant::x_13(args);	break;
        case 14: x_QVariant::x_14(args);	break;
        case 15: x_QVariant::x_15(args);	break;
        case 16: x_QVariant::x_16(args);	break;
        case 17: x_QVariant::x_17(args);	break;
        case 18: x_QVariant::x_18(args);	break;
        case 19: x_QVariant::x_19(args);	break;
        case 20: x_QVariant::x_20(args);	break;
        case 21: x_QVariant::x_21(args);	break;
        case 22: x_QVariant::x_22(args);	break;
        case 23: x_QVariant::x_23(args);	break;
        case 24: x_QVariant::x_24(args);	break;
        case 25: x_QVariant::x_25(args);	break;
        case 26: x_QVariant::x_26(args);	break;
        case 27: x_QVariant::x_27(args);	break;
        case 28: x_QVariant::x_28(args);	break;
        case 29: x_QVariant::x_29(args);	break;
        case 30: x_QVariant::x_30(args);	break;
        case 31: x_QVariant::x_31(args);	break;
        case 32: x_QVariant::x_32(args);	break;
        case 33: x_QVariant::x_33(args);	break;
        case 34: x_QVariant::x_34(args);	break;
        case 35: x_QVariant::x_35(args);	break;
        case 36: x_QVariant::x_36(args);	break;
        case 37: x_QVariant::x_37(args);	break;
        case 38: x_QVariant::x_38(args);	break;
        case 39: xself->x_39(args);	break;
        case 40: xself->x_40(args);	break;
        case 41: xself->x_41(args);	break;
        case 42: xself->x_42(args);	break;
        case 43: xself->x_43(args);	break;
        case 44: xself->x_44(args);	break;
        case 45: xself->x_45(args);	break;
        case 46: xself->x_46(args);	break;
        case 47: xself->x_47(args);	break;
        case 48: xself->x_48(args);	break;
        case 49: xself->x_49(args);	break;
        case 50: xself->x_50(args);	break;
        case 51: xself->x_51(args);	break;
        case 52: xself->x_52(args);	break;
        case 53: xself->x_53(args);	break;
        case 54: xself->x_54(args);	break;
        case 55: xself->x_55(args);	break;
        case 56: xself->x_56(args);	break;
        case 57: xself->x_57(args);	break;
        case 58: xself->x_58(args);	break;
        case 59: xself->x_59(args);	break;
        case 60: xself->x_60(args);	break;
        case 61: xself->x_61(args);	break;
        case 62: xself->x_62(args);	break;
        case 63: xself->x_63(args);	break;
        case 64: xself->x_64(args);	break;
        case 65: xself->x_65(args);	break;
        case 66: xself->x_66(args);	break;
        case 67: xself->x_67(args);	break;
        case 68: xself->x_68(args);	break;
        case 69: xself->x_69(args);	break;
        case 70: xself->x_70(args);	break;
        case 71: xself->x_71(args);	break;
        case 72: xself->x_72(args);	break;
        case 73: xself->x_73(args);	break;
        case 74: xself->x_74(args);	break;
        case 75: xself->x_75(args);	break;
        case 76: xself->x_76(args);	break;
        case 77: xself->x_77(args);	break;
        case 78: xself->x_78(args);	break;
        case 79: xself->x_79(args);	break;
        case 80: xself->x_80(args);	break;
        case 81: xself->x_81(args);	break;
        case 82: xself->x_82(args);	break;
        case 83: xself->x_83(args);	break;
        case 84: x_QVariant::x_84(args);	break;
        case 85: x_QVariant::x_85(args);	break;
        case 86: xself->x_86(args);	break;
        case 87: xself->x_87(args);	break;
        case 88: xself->x_88(args);	break;
        case 89: xself->x_89(args);	break;
        case 90: xself->x_90(args);	break;
        case 91: xself->x_91(args);	break;
        case 92: xself->x_92(args);	break;
        case 93: xself->x_93(args);	break;
        case 94: xself->x_94(args);	break;
        case 95: xself->x_95(args);	break;
        case 96: xself->x_96(args);	break;
        case 97: xself->x_97(args);	break;
        case 98: xself->x_98(args);	break;
        case 99: xself->x_99(args);	break;
        case 100: xself->x_100(args);	break;
        case 101: xself->x_101(args);	break;
        case 102: xself->x_102(args);	break;
        case 103: x_QVariant::x_103(args);	break;
        case 104: x_QVariant::x_104(args);	break;
        case 105: x_QVariant::x_105(args);	break;
        case 106: x_QVariant::x_106(args);	break;
        case 107: x_QVariant::x_107(args);	break;
        case 108: x_QVariant::x_108(args);	break;
        case 109: x_QVariant::x_109(args);	break;
        case 110: x_QVariant::x_110(args);	break;
        case 111: x_QVariant::x_111(args);	break;
        case 112: x_QVariant::x_112(args);	break;
        case 113: x_QVariant::x_113(args);	break;
        case 114: x_QVariant::x_114(args);	break;
        case 115: x_QVariant::x_115(args);	break;
        case 116: x_QVariant::x_116(args);	break;
        case 117: x_QVariant::x_117(args);	break;
        case 118: x_QVariant::x_118(args);	break;
        case 119: x_QVariant::x_119(args);	break;
        case 120: x_QVariant::x_120(args);	break;
        case 121: x_QVariant::x_121(args);	break;
        case 122: x_QVariant::x_122(args);	break;
        case 123: x_QVariant::x_123(args);	break;
        case 124: x_QVariant::x_124(args);	break;
        case 125: x_QVariant::x_125(args);	break;
        case 126: x_QVariant::x_126(args);	break;
        case 127: x_QVariant::x_127(args);	break;
        case 128: x_QVariant::x_128(args);	break;
        case 129: x_QVariant::x_129(args);	break;
        case 130: x_QVariant::x_130(args);	break;
        case 131: x_QVariant::x_131(args);	break;
        case 132: x_QVariant::x_132(args);	break;
        case 133: x_QVariant::x_133(args);	break;
        case 134: x_QVariant::x_134(args);	break;
        case 135: x_QVariant::x_135(args);	break;
        case 136: x_QVariant::x_136(args);	break;
        case 137: x_QVariant::x_137(args);	break;
        case 138: x_QVariant::x_138(args);	break;
        case 139: x_QVariant::x_139(args);	break;
        case 140: x_QVariant::x_140(args);	break;
        case 141: x_QVariant::x_141(args);	break;
        case 142: x_QVariant::x_142(args);	break;
        case 143: x_QVariant::x_143(args);	break;
        case 144: x_QVariant::x_144(args);	break;
        case 145: x_QVariant::x_145(args);	break;
        case 146: x_QVariant::x_146(args);	break;
        case 147: x_QVariant::x_147(args);	break;
        case 148: x_QVariant::x_148(args);	break;
        case 149: x_QVariant::x_149(args);	break;
        case 150: x_QVariant::x_150(args);	break;
        case 151: x_QVariant::x_151(args);	break;
        case 152: x_QVariant::x_152(args);	break;
        case 153: x_QVariant::x_153(args);	break;
        case 154: x_QVariant::x_154(args);	break;
        case 155: x_QVariant::x_155(args);	break;
        case 156: x_QVariant::x_156(args);	break;
        case 157: x_QVariant::x_157(args);	break;
        case 158: x_QVariant::x_158(args);	break;
        case 159: x_QVariant::x_159(args);	break;
        case 160: x_QVariant::x_160(args);	break;
        case 161: x_QVariant::x_161(args);	break;
        case 162: delete (QVariant*)xself;	break;
    }
}
class x_QVariantAnimation : public QVariantAnimation, public __internal_SmokeClass {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    void x_1(Smoke::Stack x) {
        // virtual const QMetaObject* metaObject() const
        if (dynamic_cast<__internal_SmokeClass*>(static_cast<QVariantAnimation*>(this))) {
            const QMetaObject* xret = ((const x_QVariantAnimation*)this)->QVariantAnimation::metaObject();
            x[0].s_class = (void*)xret;
        } else {
            const QMetaObject* xret = ((const x_QVariantAnimation*)this)->metaObject();
            x[0].s_class = (void*)xret;
        }
    }
    void x_2(Smoke::Stack x) {
        // virtual void* qt_metacast(const char*)
        if (dynamic_cast<__internal_SmokeClass*>(static_cast<QVariantAnimation*>(this))) {
            void* xret = this->QVariantAnimation::qt_metacast((const char*)x[1].s_class);
            x[0].s_class = (void*)xret;
        } else {
            void* xret = this->qt_metacast((const char*)x[1].s_class);
            x[0].s_class = (void*)xret;
        }
    }
    static void x_3(Smoke::Stack x) {
        // static QString tr(const char*, const char*)
        QString xret = QVariantAnimation::tr((const char*)x[1].s_class,(const char*)x[2].s_class);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_4(Smoke::Stack x) {
        // static QString trUtf8(const char*, const char*)
        QString xret = QVariantAnimation::trUtf8((const char*)x[1].s_class,(const char*)x[2].s_class);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_5(Smoke::Stack x) {
        // static QString tr(const char*, const char*, int)
        QString xret = QVariantAnimation::tr((const char*)x[1].s_class,(const char*)x[2].s_class,(int)x[3].s_int);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_6(Smoke::Stack x) {
        // static QString trUtf8(const char*, const char*, int)
        QString xret = QVariantAnimation::trUtf8((const char*)x[1].s_class,(const char*)x[2].s_class,(int)x[3].s_int);
        x[0].s_class = (void*)new QString(xret);
    }
    void x_7(Smoke::Stack x) {
        // virtual int qt_metacall(QMetaObject::Call, int, void**)
        if (dynamic_cast<__internal_SmokeClass*>(static_cast<QVariantAnimation*>(this))) {
            int xret = this->QVariantAnimation::qt_metacall((QMetaObject::Call)x[1].s_enum,(int)x[2].s_int,(void**)x[3].s_class);
            x[0].s_int = xret;
        } else {
            int xret = this->qt_metacall((QMetaObject::Call)x[1].s_enum,(int)x[2].s_int,(void**)x[3].s_class);
            x[0].s_int = xret;
        }
    }
    static void x_8(Smoke::Stack x) {
        // QVariantAnimation* QVariantAnimation(QObject*)
        x_QVariantAnimation* xret = new x_QVariantAnimation((QObject*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariantAnimation(QObject* x1) : QVariantAnimation(x1) {}
    void x_9(Smoke::Stack x) {
        // QVariant startValue() const
        QVariant xret = ((const x_QVariantAnimation*)this)->QVariantAnimation::startValue();
        x[0].s_class = (void*)new QVariant(xret);
    }
    void x_10(Smoke::Stack x) {
        // void setStartValue(const QVariant&)
        this->QVariantAnimation::setStartValue(*(const QVariant*)x[1].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_11(Smoke::Stack x) {
        // QVariant endValue() const
        QVariant xret = ((const x_QVariantAnimation*)this)->QVariantAnimation::endValue();
        x[0].s_class = (void*)new QVariant(xret);
    }
    void x_12(Smoke::Stack x) {
        // void setEndValue(const QVariant&)
        this->QVariantAnimation::setEndValue(*(const QVariant*)x[1].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_13(Smoke::Stack x) {
        // QVariant keyValueAt(double) const
        QVariant xret = ((const x_QVariantAnimation*)this)->QVariantAnimation::keyValueAt((double)x[1].s_double);
        x[0].s_class = (void*)new QVariant(xret);
    }
    void x_14(Smoke::Stack x) {
        // void setKeyValueAt(double, const QVariant&)
        this->QVariantAnimation::setKeyValueAt((double)x[1].s_double,*(const QVariant*)x[2].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_15(Smoke::Stack x) {
        // QVector<QPair<double,QVariant> > keyValues() const
        QVector<QPair<double,QVariant> > xret = ((const x_QVariantAnimation*)this)->QVariantAnimation::keyValues();
        x[0].s_class = (void*)new QVector<QPair<double,QVariant> >(xret);
    }
    void x_16(Smoke::Stack x) {
        // void setKeyValues(const QVector<QPair<double,QVariant> >&)
        this->QVariantAnimation::setKeyValues(*(const QVector<QPair<double,QVariant> >*)x[1].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_17(Smoke::Stack x) {
        // QVariant currentValue() const
        QVariant xret = ((const x_QVariantAnimation*)this)->QVariantAnimation::currentValue();
        x[0].s_class = (void*)new QVariant(xret);
    }
    void x_18(Smoke::Stack x) {
        // int duration() const
        if (dynamic_cast<__internal_SmokeClass*>(static_cast<QVariantAnimation*>(this))) {
            int xret = ((const x_QVariantAnimation*)this)->QVariantAnimation::duration();
            x[0].s_int = xret;
        } else {
            int xret = ((const x_QVariantAnimation*)this)->duration();
            x[0].s_int = xret;
        }
    }
    void x_19(Smoke::Stack x) {
        // void setDuration(int)
        this->QVariantAnimation::setDuration((int)x[1].s_int);
        (void)x; // noop (for compiler warning)
    }
    void x_20(Smoke::Stack x) {
        // QEasingCurve easingCurve() const
        QEasingCurve xret = ((const x_QVariantAnimation*)this)->QVariantAnimation::easingCurve();
        x[0].s_class = (void*)new QEasingCurve(xret);
    }
    void x_21(Smoke::Stack x) {
        // void setEasingCurve(const QEasingCurve&)
        this->QVariantAnimation::setEasingCurve(*(const QEasingCurve*)x[1].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_22(Smoke::Stack x) {
        // void valueChanged(const QVariant&)
        this->QVariantAnimation::valueChanged(*(const QVariant*)x[1].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_23(Smoke::Stack x) {
        // bool event(QEvent*)
        if (dynamic_cast<__internal_SmokeClass*>(static_cast<QVariantAnimation*>(this))) {
            bool xret = this->QVariantAnimation::event((QEvent*)x[1].s_class);
            x[0].s_bool = xret;
        } else {
            bool xret = this->event((QEvent*)x[1].s_class);
            x[0].s_bool = xret;
        }
    }
    void x_24(Smoke::Stack x) {
        // void updateCurrentTime(int)
        if (dynamic_cast<__internal_SmokeClass*>(static_cast<QVariantAnimation*>(this))) {
            this->QVariantAnimation::updateCurrentTime((int)x[1].s_int);
            (void)x; // noop (for compiler warning)
        } else {
            this->updateCurrentTime((int)x[1].s_int);
            (void)x; // noop (for compiler warning)
        }
    }
    void x_25(Smoke::Stack x) {
        // void updateState(QAbstractAnimation::State, QAbstractAnimation::State)
        if (dynamic_cast<__internal_SmokeClass*>(static_cast<QVariantAnimation*>(this))) {
            this->QVariantAnimation::updateState((QAbstractAnimation::State)x[1].s_enum,(QAbstractAnimation::State)x[2].s_enum);
            (void)x; // noop (for compiler warning)
        } else {
            this->updateState((QAbstractAnimation::State)x[1].s_enum,(QAbstractAnimation::State)x[2].s_enum);
            (void)x; // noop (for compiler warning)
        }
    }
    void x_26(Smoke::Stack x) {
        // virtual void updateCurrentValue(const QVariant&) = 0
        this->updateCurrentValue(*(const QVariant*)x[1].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_27(Smoke::Stack x) {
        // virtual QVariant interpolated(const QVariant&, const QVariant&, double) const
        if (dynamic_cast<__internal_SmokeClass*>(static_cast<QVariantAnimation*>(this))) {
            QVariant xret = ((const x_QVariantAnimation*)this)->QVariantAnimation::interpolated(*(const QVariant*)x[1].s_class,*(const QVariant*)x[2].s_class,(double)x[3].s_double);
            x[0].s_class = (void*)new QVariant(xret);
        } else {
            QVariant xret = ((const x_QVariantAnimation*)this)->interpolated(*(const QVariant*)x[1].s_class,*(const QVariant*)x[2].s_class,(double)x[3].s_double);
            x[0].s_class = (void*)new QVariant(xret);
        }
    }
    static void x_28(Smoke::Stack x) {
        // static QString tr(const char*)
        QString xret = QVariantAnimation::tr((const char*)x[1].s_class,(const char*)0);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_29(Smoke::Stack x) {
        // static QString trUtf8(const char*)
        QString xret = QVariantAnimation::trUtf8((const char*)x[1].s_class,(const char*)0);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_30(Smoke::Stack x) {
        // QVariantAnimation* QVariantAnimation()
        x_QVariantAnimation* xret = new x_QVariantAnimation((QObject*)0);
        x[0].s_class = (void*)xret;
    }
    static void x_31(Smoke::Stack x) {
        // static const QMetaObject staticMetaObject
        x[0].s_class = (void*)&QVariantAnimation::staticMetaObject;
    }
    virtual const QMetaObject* metaObject() const {
        Smoke::StackItem x[1];
        if (this->_binding->callMethod(5628, (void*)this, x)) return (const QMetaObject*)x[0].s_class;
        return this->QVariantAnimation::metaObject();
    }
    virtual void* qt_metacast(const char* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(5629, (void*)this, x)) return (void*)x[0].s_class;
        return this->QVariantAnimation::qt_metacast(x1);
    }
    virtual int qt_metacall(QMetaObject::Call x1, int x2, void** x3) {
        Smoke::StackItem x[4];
        x[1].s_enum = x1;
        x[2].s_int = x2;
        x[3].s_class = (void*)x3;
        if (this->_binding->callMethod(5634, (void*)this, x)) return (int)x[0].s_int;
        return this->QVariantAnimation::qt_metacall(x1, x2, x3);
    }
    virtual void updateCurrentValue(const QVariant& x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)&x1;
        this->_binding->callMethod(5653, (void*)this, x, true /*pure virtual*/);
    }
    virtual QVariant interpolated(const QVariant& x1, const QVariant& x2, double x3) const {
        Smoke::StackItem x[4];
        x[1].s_class = (void*)&x1;
        x[2].s_class = (void*)&x2;
        x[3].s_double = x3;
        if (this->_binding->callMethod(5654, (void*)this, x)) {
            QVariant* xptr = (QVariant*)x[0].s_class;
            QVariant xret(*xptr);
            delete xptr;
            return xret;
        }
        return this->QVariantAnimation::interpolated(x1, x2, x3);
    }
    virtual int duration() const {
        Smoke::StackItem x[1];
        if (this->_binding->callMethod(5645, (void*)this, x)) return (int)x[0].s_int;
        return this->QVariantAnimation::duration();
    }
    virtual void updateCurrentTime(int x1) {
        Smoke::StackItem x[2];
        x[1].s_int = x1;
        if (this->_binding->callMethod(5651, (void*)this, x)) return;
        this->QVariantAnimation::updateCurrentTime(x1);
    }
    virtual void updateState(QAbstractAnimation::State x1, QAbstractAnimation::State x2) {
        Smoke::StackItem x[3];
        x[1].s_enum = x1;
        x[2].s_enum = x2;
        if (this->_binding->callMethod(5652, (void*)this, x)) return;
        this->QVariantAnimation::updateState(x1, x2);
    }
    virtual void updateDirection(QAbstractAnimation::Direction x1) {
        Smoke::StackItem x[2];
        x[1].s_enum = x1;
        if (this->_binding->callMethod(33, (void*)this, x)) return;
        this->QAbstractAnimation::updateDirection(x1);
    }
    virtual bool event(QEvent* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(5650, (void*)this, x)) return (bool)x[0].s_bool;
        return this->QVariantAnimation::event(x1);
    }
    virtual bool eventFilter(QObject* x1, QEvent* x2) {
        Smoke::StackItem x[3];
        x[1].s_class = (void*)x1;
        x[2].s_class = (void*)x2;
        if (this->_binding->callMethod(3805, (void*)this, x)) return (bool)x[0].s_bool;
        return this->QObject::eventFilter(x1, x2);
    }
    virtual void timerEvent(QTimerEvent* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(3841, (void*)this, x)) return;
        this->QObject::timerEvent(x1);
    }
    virtual void childEvent(QChildEvent* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(3842, (void*)this, x)) return;
        this->QObject::childEvent(x1);
    }
    virtual void customEvent(QEvent* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(3843, (void*)this, x)) return;
        this->QObject::customEvent(x1);
    }
    virtual void connectNotify(const char* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(3844, (void*)this, x)) return;
        this->QObject::connectNotify(x1);
    }
    virtual void disconnectNotify(const char* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(3845, (void*)this, x)) return;
        this->QObject::disconnectNotify(x1);
    }
    ~x_QVariantAnimation() { this->_binding->deleted(140, (void*)this); }
};
void xcall_QVariantAnimation(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QVariantAnimation *xself = (x_QVariantAnimation*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: xself->x_1(args);	break;
        case 2: xself->x_2(args);	break;
        case 3: x_QVariantAnimation::x_3(args);	break;
        case 4: x_QVariantAnimation::x_4(args);	break;
        case 5: x_QVariantAnimation::x_5(args);	break;
        case 6: x_QVariantAnimation::x_6(args);	break;
        case 7: xself->x_7(args);	break;
        case 8: x_QVariantAnimation::x_8(args);	break;
        case 9: xself->x_9(args);	break;
        case 10: xself->x_10(args);	break;
        case 11: xself->x_11(args);	break;
        case 12: xself->x_12(args);	break;
        case 13: xself->x_13(args);	break;
        case 14: xself->x_14(args);	break;
        case 15: xself->x_15(args);	break;
        case 16: xself->x_16(args);	break;
        case 17: xself->x_17(args);	break;
        case 18: xself->x_18(args);	break;
        case 19: xself->x_19(args);	break;
        case 20: xself->x_20(args);	break;
        case 21: xself->x_21(args);	break;
        case 22: xself->x_22(args);	break;
        case 23: xself->x_23(args);	break;
        case 24: xself->x_24(args);	break;
        case 25: xself->x_25(args);	break;
        case 26: xself->x_26(args);	break;
        case 27: xself->x_27(args);	break;
        case 28: x_QVariantAnimation::x_28(args);	break;
        case 29: x_QVariantAnimation::x_29(args);	break;
        case 30: x_QVariantAnimation::x_30(args);	break;
        case 31: x_QVariantAnimation::x_31(args);	break;
        case 32: delete (QVariantAnimation*)xself;	break;
    }
}
class x_QVariantComparisonHelper : public QVariantComparisonHelper {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    static void x_1(Smoke::Stack x) {
        // QVariantComparisonHelper* QVariantComparisonHelper(const QVariant&)
        x_QVariantComparisonHelper* xret = new x_QVariantComparisonHelper(*(const QVariant*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariantComparisonHelper(const QVariant& x1) : QVariantComparisonHelper(x1) {}
    static void x_2(Smoke::Stack x) {
        // QVariantComparisonHelper* QVariantComparisonHelper(const QVariantComparisonHelper&)
        x_QVariantComparisonHelper* xret = new x_QVariantComparisonHelper(*(const QVariantComparisonHelper*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QVariantComparisonHelper(const QVariantComparisonHelper& x1) : QVariantComparisonHelper(x1) {}
    ~x_QVariantComparisonHelper() { this->_binding->deleted(141, (void*)this); }
};
void xcall_QVariantComparisonHelper(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QVariantComparisonHelper *xself = (x_QVariantComparisonHelper*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: x_QVariantComparisonHelper::x_1(args);	break;
        case 2: x_QVariantComparisonHelper::x_2(args);	break;
        case 3: delete (QVariantComparisonHelper*)xself;	break;
    }
}
class x_QWriteLocker : public QWriteLocker {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    static void x_1(Smoke::Stack x) {
        // QWriteLocker* QWriteLocker(QReadWriteLock*)
        x_QWriteLocker* xret = new x_QWriteLocker((QReadWriteLock*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QWriteLocker(QReadWriteLock* x1) : QWriteLocker(x1) {}
    void x_2(Smoke::Stack x) {
        // void unlock()
        this->QWriteLocker::unlock();
        (void)x; // noop (for compiler warning)
    }
    void x_3(Smoke::Stack x) {
        // void relock()
        this->QWriteLocker::relock();
        (void)x; // noop (for compiler warning)
    }
    void x_4(Smoke::Stack x) {
        // QReadWriteLock* readWriteLock() const
        QReadWriteLock* xret = ((const x_QWriteLocker*)this)->QWriteLocker::readWriteLock();
        x[0].s_class = (void*)xret;
    }
    ~x_QWriteLocker() { this->_binding->deleted(143, (void*)this); }
};
void xcall_QWriteLocker(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QWriteLocker *xself = (x_QWriteLocker*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: x_QWriteLocker::x_1(args);	break;
        case 2: xself->x_2(args);	break;
        case 3: xself->x_3(args);	break;
        case 4: xself->x_4(args);	break;
        case 5: delete (QWriteLocker*)xself;	break;
    }
}
class x_QXmlStreamAttribute : public QXmlStreamAttribute {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    static void x_1(Smoke::Stack x) {
        // QXmlStreamAttribute* QXmlStreamAttribute()
        x_QXmlStreamAttribute* xret = new x_QXmlStreamAttribute();
        x[0].s_class = (void*)xret;
    }
    explicit x_QXmlStreamAttribute() : QXmlStreamAttribute() {}
    static void x_2(Smoke::Stack x) {
        // QXmlStreamAttribute* QXmlStreamAttribute(const QString&, const QString&)
        x_QXmlStreamAttribute* xret = new x_QXmlStreamAttribute(*(const QString*)x[1].s_class,*(const QString*)x[2].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QXmlStreamAttribute(const QString& x1, const QString& x2) : QXmlStreamAttribute(x1, x2) {}
    static void x_3(Smoke::Stack x) {
        // QXmlStreamAttribute* QXmlStreamAttribute(const QString&, const QString&, const QString&)
        x_QXmlStreamAttribute* xret = new x_QXmlStreamAttribute(*(const QString*)x[1].s_class,*(const QString*)x[2].s_class,*(const QString*)x[3].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QXmlStreamAttribute(const QString& x1, const QString& x2, const QString& x3) : QXmlStreamAttribute(x1, x2, x3) {}
    static void x_4(Smoke::Stack x) {
        // QXmlStreamAttribute* QXmlStreamAttribute(const QXmlStreamAttribute&)
        x_QXmlStreamAttribute* xret = new x_QXmlStreamAttribute(*(const QXmlStreamAttribute*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QXmlStreamAttribute(const QXmlStreamAttribute& x1) : QXmlStreamAttribute(x1) {}
    void x_5(Smoke::Stack x) {
        // QXmlStreamAttribute& operator=(const QXmlStreamAttribute&)
        QXmlStreamAttribute& xret = this->QXmlStreamAttribute::operator=(*(const QXmlStreamAttribute*)x[1].s_class);
        x[0].s_class = (void*)&xret;
    }
    void x_6(Smoke::Stack x) {
        // QStringRef namespaceUri() const
        QStringRef xret = ((const x_QXmlStreamAttribute*)this)->QXmlStreamAttribute::namespaceUri();
        x[0].s_class = (void*)new QStringRef(xret);
    }
    void x_7(Smoke::Stack x) {
        // QStringRef name() const
        QStringRef xret = ((const x_QXmlStreamAttribute*)this)->QXmlStreamAttribute::name();
        x[0].s_class = (void*)new QStringRef(xret);
    }
    void x_8(Smoke::Stack x) {
        // QStringRef qualifiedName() const
        QStringRef xret = ((const x_QXmlStreamAttribute*)this)->QXmlStreamAttribute::qualifiedName();
        x[0].s_class = (void*)new QStringRef(xret);
    }
    void x_9(Smoke::Stack x) {
        // QStringRef prefix() const
        QStringRef xret = ((const x_QXmlStreamAttribute*)this)->QXmlStreamAttribute::prefix();
        x[0].s_class = (void*)new QStringRef(xret);
    }
    void x_10(Smoke::Stack x) {
        // QStringRef value() const
        QStringRef xret = ((const x_QXmlStreamAttribute*)this)->QXmlStreamAttribute::value();
        x[0].s_class = (void*)new QStringRef(xret);
    }
    void x_11(Smoke::Stack x) {
        // bool isDefault() const
        bool xret = ((const x_QXmlStreamAttribute*)this)->QXmlStreamAttribute::isDefault();
        x[0].s_bool = xret;
    }
    void x_12(Smoke::Stack x) {
        // bool operator==(const QXmlStreamAttribute&) const
        bool xret = ((const x_QXmlStreamAttribute*)this)->QXmlStreamAttribute::operator==(*(const QXmlStreamAttribute*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_13(Smoke::Stack x) {
        // bool operator!=(const QXmlStreamAttribute&) const
        bool xret = ((const x_QXmlStreamAttribute*)this)->QXmlStreamAttribute::operator!=(*(const QXmlStreamAttribute*)x[1].s_class);
        x[0].s_bool = xret;
    }
    ~x_QXmlStreamAttribute() { this->_binding->deleted(144, (void*)this); }
};
void xcall_QXmlStreamAttribute(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QXmlStreamAttribute *xself = (x_QXmlStreamAttribute*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: x_QXmlStreamAttribute::x_1(args);	break;
        case 2: x_QXmlStreamAttribute::x_2(args);	break;
        case 3: x_QXmlStreamAttribute::x_3(args);	break;
        case 4: x_QXmlStreamAttribute::x_4(args);	break;
        case 5: xself->x_5(args);	break;
        case 6: xself->x_6(args);	break;
        case 7: xself->x_7(args);	break;
        case 8: xself->x_8(args);	break;
        case 9: xself->x_9(args);	break;
        case 10: xself->x_10(args);	break;
        case 11: xself->x_11(args);	break;
        case 12: xself->x_12(args);	break;
        case 13: xself->x_13(args);	break;
        case 14: delete (QXmlStreamAttribute*)xself;	break;
    }
}
class x_QXmlStreamAttributes : public QXmlStreamAttributes {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    static void x_1(Smoke::Stack x) {
        // QXmlStreamAttributes* QXmlStreamAttributes()
        x_QXmlStreamAttributes* xret = new x_QXmlStreamAttributes();
        x[0].s_class = (void*)xret;
    }
    explicit x_QXmlStreamAttributes() : QXmlStreamAttributes() {}
    void x_2(Smoke::Stack x) {
        // QStringRef value(const QString&, const QString&) const
        QStringRef xret = ((const x_QXmlStreamAttributes*)this)->QXmlStreamAttributes::value(*(const QString*)x[1].s_class,*(const QString*)x[2].s_class);
        x[0].s_class = (void*)new QStringRef(xret);
    }
    void x_3(Smoke::Stack x) {
        // QStringRef value(const QString&, const QLatin1String&) const
        QStringRef xret = ((const x_QXmlStreamAttributes*)this)->QXmlStreamAttributes::value(*(const QString*)x[1].s_class,*(const QLatin1String*)x[2].s_class);
        x[0].s_class = (void*)new QStringRef(xret);
    }
    void x_4(Smoke::Stack x) {
        // QStringRef value(const QLatin1String&, const QLatin1String&) const
        QStringRef xret = ((const x_QXmlStreamAttributes*)this)->QXmlStreamAttributes::value(*(const QLatin1String*)x[1].s_class,*(const QLatin1String*)x[2].s_class);
        x[0].s_class = (void*)new QStringRef(xret);
    }
    void x_5(Smoke::Stack x) {
        // QStringRef value(const QString&) const
        QStringRef xret = ((const x_QXmlStreamAttributes*)this)->QXmlStreamAttributes::value(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)new QStringRef(xret);
    }
    void x_6(Smoke::Stack x) {
        // QStringRef value(const QLatin1String&) const
        QStringRef xret = ((const x_QXmlStreamAttributes*)this)->QXmlStreamAttributes::value(*(const QLatin1String*)x[1].s_class);
        x[0].s_class = (void*)new QStringRef(xret);
    }
    void x_7(Smoke::Stack x) {
        // void append(const QString&, const QString&, const QString&)
        this->QXmlStreamAttributes::append(*(const QString*)x[1].s_class,*(const QString*)x[2].s_class,*(const QString*)x[3].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_8(Smoke::Stack x) {
        // void append(const QString&, const QString&)
        this->QXmlStreamAttributes::append(*(const QString*)x[1].s_class,*(const QString*)x[2].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_9(Smoke::Stack x) {
        // bool hasAttribute(const QString&) const
        bool xret = ((const x_QXmlStreamAttributes*)this)->QXmlStreamAttributes::hasAttribute(*(const QString*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_10(Smoke::Stack x) {
        // bool hasAttribute(const QLatin1String&) const
        bool xret = ((const x_QXmlStreamAttributes*)this)->QXmlStreamAttributes::hasAttribute(*(const QLatin1String*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_11(Smoke::Stack x) {
        // bool hasAttribute(const QString&, const QString&) const
        bool xret = ((const x_QXmlStreamAttributes*)this)->QXmlStreamAttributes::hasAttribute(*(const QString*)x[1].s_class,*(const QString*)x[2].s_class);
        x[0].s_bool = xret;
    }
    static void x_12(Smoke::Stack x) {
        // QXmlStreamAttributes* QXmlStreamAttributes(const QXmlStreamAttributes&)
        x_QXmlStreamAttributes* xret = new x_QXmlStreamAttributes(*(const QXmlStreamAttributes*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QXmlStreamAttributes(const QXmlStreamAttributes& x1) : QXmlStreamAttributes(x1) {}
    ~x_QXmlStreamAttributes() { this->_binding->deleted(145, (void*)this); }
};
void xcall_QXmlStreamAttributes(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QXmlStreamAttributes *xself = (x_QXmlStreamAttributes*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: x_QXmlStreamAttributes::x_1(args);	break;
        case 2: xself->x_2(args);	break;
        case 3: xself->x_3(args);	break;
        case 4: xself->x_4(args);	break;
        case 5: xself->x_5(args);	break;
        case 6: xself->x_6(args);	break;
        case 7: xself->x_7(args);	break;
        case 8: xself->x_8(args);	break;
        case 9: xself->x_9(args);	break;
        case 10: xself->x_10(args);	break;
        case 11: xself->x_11(args);	break;
        case 12: x_QXmlStreamAttributes::x_12(args);	break;
        case 13: delete (QXmlStreamAttributes*)xself;	break;
    }
}

}
