//Auto-generated by /home/vagrant/.gem/ruby/2.7.0/gems/rock-qtbindings-4.8.6.5/ext/build/generator/bin/smokegen. DO NOT EDIT.
#include <qtcore_includes.h>
#include <typeinfo>

#include <smoke.h>
#include <qtcore_smoke.h>

class __internal_SmokeClass {};

namespace __smokeqtcore {

class x_QDir : public QDir {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    static void x_1(Smoke::Stack x) {
        // QDir* QDir(const QDir&)
        x_QDir* xret = new x_QDir(*(const QDir*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QDir(const QDir& x1) : QDir(x1) {}
    static void x_2(Smoke::Stack x) {
        // QDir* QDir(const QString&)
        x_QDir* xret = new x_QDir(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QDir(const QString& x1) : QDir(x1) {}
    static void x_3(Smoke::Stack x) {
        // QDir* QDir(const QString&, const QString&, QFlags<QDir::SortFlag>, QFlags<QDir::Filter>)
        x_QDir* xret = new x_QDir(*(const QString*)x[1].s_class,*(const QString*)x[2].s_class,(QFlags<QDir::SortFlag>)x[3].s_uint,(QFlags<QDir::Filter>)x[4].s_uint);
        x[0].s_class = (void*)xret;
    }
    explicit x_QDir(const QString& x1, const QString& x2, QFlags<QDir::SortFlag> x3, QFlags<QDir::Filter> x4) : QDir(x1, x2, x3, x4) {}
    void x_4(Smoke::Stack x) {
        // QDir& operator=(const QDir&)
        QDir& xret = this->QDir::operator=(*(const QDir*)x[1].s_class);
        x[0].s_class = (void*)&xret;
    }
    void x_5(Smoke::Stack x) {
        // QDir& operator=(const QString&)
        QDir& xret = this->QDir::operator=(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)&xret;
    }
    void x_6(Smoke::Stack x) {
        // void setPath(const QString&)
        this->QDir::setPath(*(const QString*)x[1].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_7(Smoke::Stack x) {
        // QString path() const
        QString xret = ((const x_QDir*)this)->QDir::path();
        x[0].s_class = (void*)new QString(xret);
    }
    void x_8(Smoke::Stack x) {
        // QString absolutePath() const
        QString xret = ((const x_QDir*)this)->QDir::absolutePath();
        x[0].s_class = (void*)new QString(xret);
    }
    void x_9(Smoke::Stack x) {
        // QString canonicalPath() const
        QString xret = ((const x_QDir*)this)->QDir::canonicalPath();
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_10(Smoke::Stack x) {
        // static void addResourceSearchPath(const QString&)
        QDir::addResourceSearchPath(*(const QString*)x[1].s_class);
        (void)x; // noop (for compiler warning)
    }
    static void x_11(Smoke::Stack x) {
        // static void setSearchPaths(const QString&, const QStringList&)
        QDir::setSearchPaths(*(const QString*)x[1].s_class,*(const QStringList*)x[2].s_class);
        (void)x; // noop (for compiler warning)
    }
    static void x_12(Smoke::Stack x) {
        // static void addSearchPath(const QString&, const QString&)
        QDir::addSearchPath(*(const QString*)x[1].s_class,*(const QString*)x[2].s_class);
        (void)x; // noop (for compiler warning)
    }
    static void x_13(Smoke::Stack x) {
        // static QStringList searchPaths(const QString&)
        QStringList xret = QDir::searchPaths(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)new QStringList(xret);
    }
    void x_14(Smoke::Stack x) {
        // QString dirName() const
        QString xret = ((const x_QDir*)this)->QDir::dirName();
        x[0].s_class = (void*)new QString(xret);
    }
    void x_15(Smoke::Stack x) {
        // QString filePath(const QString&) const
        QString xret = ((const x_QDir*)this)->QDir::filePath(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)new QString(xret);
    }
    void x_16(Smoke::Stack x) {
        // QString absoluteFilePath(const QString&) const
        QString xret = ((const x_QDir*)this)->QDir::absoluteFilePath(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)new QString(xret);
    }
    void x_17(Smoke::Stack x) {
        // QString relativeFilePath(const QString&) const
        QString xret = ((const x_QDir*)this)->QDir::relativeFilePath(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_18(Smoke::Stack x) {
        // static QString convertSeparators(const QString&)
        QString xret = QDir::convertSeparators(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_19(Smoke::Stack x) {
        // static QString toNativeSeparators(const QString&)
        QString xret = QDir::toNativeSeparators(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_20(Smoke::Stack x) {
        // static QString fromNativeSeparators(const QString&)
        QString xret = QDir::fromNativeSeparators(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)new QString(xret);
    }
    void x_21(Smoke::Stack x) {
        // bool cd(const QString&)
        bool xret = this->QDir::cd(*(const QString*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_22(Smoke::Stack x) {
        // bool cdUp()
        bool xret = this->QDir::cdUp();
        x[0].s_bool = xret;
    }
    void x_23(Smoke::Stack x) {
        // QStringList nameFilters() const
        QStringList xret = ((const x_QDir*)this)->QDir::nameFilters();
        x[0].s_class = (void*)new QStringList(xret);
    }
    void x_24(Smoke::Stack x) {
        // void setNameFilters(const QStringList&)
        this->QDir::setNameFilters(*(const QStringList*)x[1].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_25(Smoke::Stack x) {
        // QFlags<QDir::Filter> filter() const
        QFlags<QDir::Filter> xret = ((const x_QDir*)this)->QDir::filter();
        x[0].s_uint = (uint)xret;
    }
    void x_26(Smoke::Stack x) {
        // void setFilter(QFlags<QDir::Filter>)
        this->QDir::setFilter((QFlags<QDir::Filter>)x[1].s_uint);
        (void)x; // noop (for compiler warning)
    }
    void x_27(Smoke::Stack x) {
        // QFlags<QDir::SortFlag> sorting() const
        QFlags<QDir::SortFlag> xret = ((const x_QDir*)this)->QDir::sorting();
        x[0].s_uint = (uint)xret;
    }
    void x_28(Smoke::Stack x) {
        // void setSorting(QFlags<QDir::SortFlag>)
        this->QDir::setSorting((QFlags<QDir::SortFlag>)x[1].s_uint);
        (void)x; // noop (for compiler warning)
    }
    void x_29(Smoke::Stack x) {
        // unsigned int count() const
        unsigned int xret = ((const x_QDir*)this)->QDir::count();
        x[0].s_uint = xret;
    }
    void x_30(Smoke::Stack x) {
        // QString operator[](int) const
        QString xret = ((const x_QDir*)this)->QDir::operator[]((int)x[1].s_int);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_31(Smoke::Stack x) {
        // static QStringList nameFiltersFromString(const QString&)
        QStringList xret = QDir::nameFiltersFromString(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)new QStringList(xret);
    }
    void x_32(Smoke::Stack x) {
        // QStringList entryList(QFlags<QDir::Filter>, QFlags<QDir::SortFlag>) const
        QStringList xret = ((const x_QDir*)this)->QDir::entryList((QFlags<QDir::Filter>)x[1].s_uint,(QFlags<QDir::SortFlag>)x[2].s_uint);
        x[0].s_class = (void*)new QStringList(xret);
    }
    void x_33(Smoke::Stack x) {
        // QStringList entryList(const QStringList&, QFlags<QDir::Filter>, QFlags<QDir::SortFlag>) const
        QStringList xret = ((const x_QDir*)this)->QDir::entryList(*(const QStringList*)x[1].s_class,(QFlags<QDir::Filter>)x[2].s_uint,(QFlags<QDir::SortFlag>)x[3].s_uint);
        x[0].s_class = (void*)new QStringList(xret);
    }
    void x_34(Smoke::Stack x) {
        // QList<QFileInfo> entryInfoList(QFlags<QDir::Filter>, QFlags<QDir::SortFlag>) const
        QList<QFileInfo> xret = ((const x_QDir*)this)->QDir::entryInfoList((QFlags<QDir::Filter>)x[1].s_uint,(QFlags<QDir::SortFlag>)x[2].s_uint);
        x[0].s_class = (void*)new QList<QFileInfo>(xret);
    }
    void x_35(Smoke::Stack x) {
        // QList<QFileInfo> entryInfoList(const QStringList&, QFlags<QDir::Filter>, QFlags<QDir::SortFlag>) const
        QList<QFileInfo> xret = ((const x_QDir*)this)->QDir::entryInfoList(*(const QStringList*)x[1].s_class,(QFlags<QDir::Filter>)x[2].s_uint,(QFlags<QDir::SortFlag>)x[3].s_uint);
        x[0].s_class = (void*)new QList<QFileInfo>(xret);
    }
    void x_36(Smoke::Stack x) {
        // bool mkdir(const QString&) const
        bool xret = ((const x_QDir*)this)->QDir::mkdir(*(const QString*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_37(Smoke::Stack x) {
        // bool rmdir(const QString&) const
        bool xret = ((const x_QDir*)this)->QDir::rmdir(*(const QString*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_38(Smoke::Stack x) {
        // bool mkpath(const QString&) const
        bool xret = ((const x_QDir*)this)->QDir::mkpath(*(const QString*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_39(Smoke::Stack x) {
        // bool rmpath(const QString&) const
        bool xret = ((const x_QDir*)this)->QDir::rmpath(*(const QString*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_40(Smoke::Stack x) {
        // bool isReadable() const
        bool xret = ((const x_QDir*)this)->QDir::isReadable();
        x[0].s_bool = xret;
    }
    void x_41(Smoke::Stack x) {
        // bool exists() const
        bool xret = ((const x_QDir*)this)->QDir::exists();
        x[0].s_bool = xret;
    }
    void x_42(Smoke::Stack x) {
        // bool isRoot() const
        bool xret = ((const x_QDir*)this)->QDir::isRoot();
        x[0].s_bool = xret;
    }
    static void x_43(Smoke::Stack x) {
        // static bool isRelativePath(const QString&)
        bool xret = QDir::isRelativePath(*(const QString*)x[1].s_class);
        x[0].s_bool = xret;
    }
    static void x_44(Smoke::Stack x) {
        // static bool isAbsolutePath(const QString&)
        bool xret = QDir::isAbsolutePath(*(const QString*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_45(Smoke::Stack x) {
        // bool isRelative() const
        bool xret = ((const x_QDir*)this)->QDir::isRelative();
        x[0].s_bool = xret;
    }
    void x_46(Smoke::Stack x) {
        // bool isAbsolute() const
        bool xret = ((const x_QDir*)this)->QDir::isAbsolute();
        x[0].s_bool = xret;
    }
    void x_47(Smoke::Stack x) {
        // bool makeAbsolute()
        bool xret = this->QDir::makeAbsolute();
        x[0].s_bool = xret;
    }
    void x_48(Smoke::Stack x) {
        // bool operator==(const QDir&) const
        bool xret = ((const x_QDir*)this)->QDir::operator==(*(const QDir*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_49(Smoke::Stack x) {
        // bool operator!=(const QDir&) const
        bool xret = ((const x_QDir*)this)->QDir::operator!=(*(const QDir*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_50(Smoke::Stack x) {
        // bool remove(const QString&)
        bool xret = this->QDir::remove(*(const QString*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_51(Smoke::Stack x) {
        // bool rename(const QString&, const QString&)
        bool xret = this->QDir::rename(*(const QString*)x[1].s_class,*(const QString*)x[2].s_class);
        x[0].s_bool = xret;
    }
    void x_52(Smoke::Stack x) {
        // bool exists(const QString&) const
        bool xret = ((const x_QDir*)this)->QDir::exists(*(const QString*)x[1].s_class);
        x[0].s_bool = xret;
    }
    static void x_53(Smoke::Stack x) {
        // static QList<QFileInfo> drives()
        QList<QFileInfo> xret = QDir::drives();
        x[0].s_class = (void*)new QList<QFileInfo>(xret);
    }
    static void x_54(Smoke::Stack x) {
        // static QChar separator()
        QChar xret = QDir::separator();
        x[0].s_class = (void*)new QChar(xret);
    }
    static void x_55(Smoke::Stack x) {
        // static bool setCurrent(const QString&)
        bool xret = QDir::setCurrent(*(const QString*)x[1].s_class);
        x[0].s_bool = xret;
    }
    static void x_56(Smoke::Stack x) {
        // static QDir current()
        QDir xret = QDir::current();
        x[0].s_class = (void*)new QDir(xret);
    }
    static void x_57(Smoke::Stack x) {
        // static QString currentPath()
        QString xret = QDir::currentPath();
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_58(Smoke::Stack x) {
        // static QDir home()
        QDir xret = QDir::home();
        x[0].s_class = (void*)new QDir(xret);
    }
    static void x_59(Smoke::Stack x) {
        // static QString homePath()
        QString xret = QDir::homePath();
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_60(Smoke::Stack x) {
        // static QDir root()
        QDir xret = QDir::root();
        x[0].s_class = (void*)new QDir(xret);
    }
    static void x_61(Smoke::Stack x) {
        // static QString rootPath()
        QString xret = QDir::rootPath();
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_62(Smoke::Stack x) {
        // static QDir temp()
        QDir xret = QDir::temp();
        x[0].s_class = (void*)new QDir(xret);
    }
    static void x_63(Smoke::Stack x) {
        // static QString tempPath()
        QString xret = QDir::tempPath();
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_64(Smoke::Stack x) {
        // static bool match(const QStringList&, const QString&)
        bool xret = QDir::match(*(const QStringList*)x[1].s_class,*(const QString*)x[2].s_class);
        x[0].s_bool = xret;
    }
    static void x_65(Smoke::Stack x) {
        // static bool match(const QString&, const QString&)
        bool xret = QDir::match(*(const QString*)x[1].s_class,*(const QString*)x[2].s_class);
        x[0].s_bool = xret;
    }
    static void x_66(Smoke::Stack x) {
        // static QString cleanPath(const QString&)
        QString xret = QDir::cleanPath(*(const QString*)x[1].s_class);
        x[0].s_class = (void*)new QString(xret);
    }
    void x_67(Smoke::Stack x) {
        // void refresh() const
        ((const x_QDir*)this)->QDir::refresh();
        (void)x; // noop (for compiler warning)
    }
    static void x_68(Smoke::Stack x) {
        // QDir* QDir()
        x_QDir* xret = new x_QDir((const QString&)QString());
        x[0].s_class = (void*)xret;
    }
    static void x_69(Smoke::Stack x) {
        // QDir* QDir(const QString&, const QString&)
        x_QDir* xret = new x_QDir(*(const QString*)x[1].s_class,*(const QString*)x[2].s_class,(QFlags<QDir::SortFlag>)QDir::SortFlags(Name|IgnoreCase),(QFlags<QDir::Filter>)QDir::AllEntries);
        x[0].s_class = (void*)xret;
    }
    static void x_70(Smoke::Stack x) {
        // QDir* QDir(const QString&, const QString&, QFlags<QDir::SortFlag>)
        x_QDir* xret = new x_QDir(*(const QString*)x[1].s_class,*(const QString*)x[2].s_class,(QFlags<QDir::SortFlag>)x[3].s_uint,(QFlags<QDir::Filter>)QDir::AllEntries);
        x[0].s_class = (void*)xret;
    }
    void x_71(Smoke::Stack x) {
        // QStringList entryList() const
        QStringList xret = ((const x_QDir*)this)->QDir::entryList((QFlags<QDir::Filter>)QDir::NoFilter,(QFlags<QDir::SortFlag>)QDir::NoSort);
        x[0].s_class = (void*)new QStringList(xret);
    }
    void x_72(Smoke::Stack x) {
        // QStringList entryList(QFlags<QDir::Filter>) const
        QStringList xret = ((const x_QDir*)this)->QDir::entryList((QFlags<QDir::Filter>)x[1].s_uint,(QFlags<QDir::SortFlag>)QDir::NoSort);
        x[0].s_class = (void*)new QStringList(xret);
    }
    void x_73(Smoke::Stack x) {
        // QStringList entryList(const QStringList&) const
        QStringList xret = ((const x_QDir*)this)->QDir::entryList(*(const QStringList*)x[1].s_class,(QFlags<QDir::Filter>)QDir::NoFilter,(QFlags<QDir::SortFlag>)QDir::NoSort);
        x[0].s_class = (void*)new QStringList(xret);
    }
    void x_74(Smoke::Stack x) {
        // QStringList entryList(const QStringList&, QFlags<QDir::Filter>) const
        QStringList xret = ((const x_QDir*)this)->QDir::entryList(*(const QStringList*)x[1].s_class,(QFlags<QDir::Filter>)x[2].s_uint,(QFlags<QDir::SortFlag>)QDir::NoSort);
        x[0].s_class = (void*)new QStringList(xret);
    }
    void x_75(Smoke::Stack x) {
        // QList<QFileInfo> entryInfoList() const
        QList<QFileInfo> xret = ((const x_QDir*)this)->QDir::entryInfoList((QFlags<QDir::Filter>)QDir::NoFilter,(QFlags<QDir::SortFlag>)QDir::NoSort);
        x[0].s_class = (void*)new QList<QFileInfo>(xret);
    }
    void x_76(Smoke::Stack x) {
        // QList<QFileInfo> entryInfoList(QFlags<QDir::Filter>) const
        QList<QFileInfo> xret = ((const x_QDir*)this)->QDir::entryInfoList((QFlags<QDir::Filter>)x[1].s_uint,(QFlags<QDir::SortFlag>)QDir::NoSort);
        x[0].s_class = (void*)new QList<QFileInfo>(xret);
    }
    void x_77(Smoke::Stack x) {
        // QList<QFileInfo> entryInfoList(const QStringList&) const
        QList<QFileInfo> xret = ((const x_QDir*)this)->QDir::entryInfoList(*(const QStringList*)x[1].s_class,(QFlags<QDir::Filter>)QDir::NoFilter,(QFlags<QDir::SortFlag>)QDir::NoSort);
        x[0].s_class = (void*)new QList<QFileInfo>(xret);
    }
    void x_78(Smoke::Stack x) {
        // QList<QFileInfo> entryInfoList(const QStringList&, QFlags<QDir::Filter>) const
        QList<QFileInfo> xret = ((const x_QDir*)this)->QDir::entryInfoList(*(const QStringList*)x[1].s_class,(QFlags<QDir::Filter>)x[2].s_uint,(QFlags<QDir::SortFlag>)QDir::NoSort);
        x[0].s_class = (void*)new QList<QFileInfo>(xret);
    }
    static void x_79(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Dirs;
    }
    static void x_80(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Files;
    }
    static void x_81(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Drives;
    }
    static void x_82(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::NoSymLinks;
    }
    static void x_83(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::AllEntries;
    }
    static void x_84(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::TypeMask;
    }
    static void x_85(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Readable;
    }
    static void x_86(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Writable;
    }
    static void x_87(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Executable;
    }
    static void x_88(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::PermissionMask;
    }
    static void x_89(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Modified;
    }
    static void x_90(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Hidden;
    }
    static void x_91(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::System;
    }
    static void x_92(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::AccessMask;
    }
    static void x_93(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::AllDirs;
    }
    static void x_94(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::CaseSensitive;
    }
    static void x_95(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::NoDotAndDotDot;
    }
    static void x_96(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::NoDot;
    }
    static void x_97(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::NoDotDot;
    }
    static void x_98(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::NoFilter;
    }
    static void x_99(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Name;
    }
    static void x_100(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Time;
    }
    static void x_101(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Size;
    }
    static void x_102(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Unsorted;
    }
    static void x_103(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::SortByMask;
    }
    static void x_104(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::DirsFirst;
    }
    static void x_105(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Reversed;
    }
    static void x_106(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::IgnoreCase;
    }
    static void x_107(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::DirsLast;
    }
    static void x_108(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::LocaleAware;
    }
    static void x_109(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::Type;
    }
    static void x_110(Smoke::Stack x) {
        x[0].s_enum = (long)QDir::NoSort;
    }
    static void xenum_operation(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
        switch(xtype) {
        case 86: //QDir::Filter
            switch(xop) {
                case Smoke::EnumNew:
                    xdata = (void*)new QDir::Filter;
                    break;
                case Smoke::EnumDelete:
                    delete (QDir::Filter*)xdata;
                    break;
                case Smoke::EnumFromLong:
                    *(QDir::Filter*)xdata = (QDir::Filter)xvalue;
                    break;
                case Smoke::EnumToLong:
                    xvalue = (long)*(QDir::Filter*)xdata;
                    break;
            }
            break;
        case 87: //QDir::SortFlag
            switch(xop) {
                case Smoke::EnumNew:
                    xdata = (void*)new QDir::SortFlag;
                    break;
                case Smoke::EnumDelete:
                    delete (QDir::SortFlag*)xdata;
                    break;
                case Smoke::EnumFromLong:
                    *(QDir::SortFlag*)xdata = (QDir::SortFlag)xvalue;
                    break;
                case Smoke::EnumToLong:
                    xvalue = (long)*(QDir::SortFlag*)xdata;
                    break;
            }
            break;
        }
    }
    ~x_QDir() { this->_binding->deleted(36, (void*)this); }
};
void xenum_QDir(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
    x_QDir::xenum_operation(xop, xtype, xdata, xvalue);
}
void xcall_QDir(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QDir *xself = (x_QDir*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: x_QDir::x_1(args);	break;
        case 2: x_QDir::x_2(args);	break;
        case 3: x_QDir::x_3(args);	break;
        case 4: xself->x_4(args);	break;
        case 5: xself->x_5(args);	break;
        case 6: xself->x_6(args);	break;
        case 7: xself->x_7(args);	break;
        case 8: xself->x_8(args);	break;
        case 9: xself->x_9(args);	break;
        case 10: x_QDir::x_10(args);	break;
        case 11: x_QDir::x_11(args);	break;
        case 12: x_QDir::x_12(args);	break;
        case 13: x_QDir::x_13(args);	break;
        case 14: xself->x_14(args);	break;
        case 15: xself->x_15(args);	break;
        case 16: xself->x_16(args);	break;
        case 17: xself->x_17(args);	break;
        case 18: x_QDir::x_18(args);	break;
        case 19: x_QDir::x_19(args);	break;
        case 20: x_QDir::x_20(args);	break;
        case 21: xself->x_21(args);	break;
        case 22: xself->x_22(args);	break;
        case 23: xself->x_23(args);	break;
        case 24: xself->x_24(args);	break;
        case 25: xself->x_25(args);	break;
        case 26: xself->x_26(args);	break;
        case 27: xself->x_27(args);	break;
        case 28: xself->x_28(args);	break;
        case 29: xself->x_29(args);	break;
        case 30: xself->x_30(args);	break;
        case 31: x_QDir::x_31(args);	break;
        case 32: xself->x_32(args);	break;
        case 33: xself->x_33(args);	break;
        case 34: xself->x_34(args);	break;
        case 35: xself->x_35(args);	break;
        case 36: xself->x_36(args);	break;
        case 37: xself->x_37(args);	break;
        case 38: xself->x_38(args);	break;
        case 39: xself->x_39(args);	break;
        case 40: xself->x_40(args);	break;
        case 41: xself->x_41(args);	break;
        case 42: xself->x_42(args);	break;
        case 43: x_QDir::x_43(args);	break;
        case 44: x_QDir::x_44(args);	break;
        case 45: xself->x_45(args);	break;
        case 46: xself->x_46(args);	break;
        case 47: xself->x_47(args);	break;
        case 48: xself->x_48(args);	break;
        case 49: xself->x_49(args);	break;
        case 50: xself->x_50(args);	break;
        case 51: xself->x_51(args);	break;
        case 52: xself->x_52(args);	break;
        case 53: x_QDir::x_53(args);	break;
        case 54: x_QDir::x_54(args);	break;
        case 55: x_QDir::x_55(args);	break;
        case 56: x_QDir::x_56(args);	break;
        case 57: x_QDir::x_57(args);	break;
        case 58: x_QDir::x_58(args);	break;
        case 59: x_QDir::x_59(args);	break;
        case 60: x_QDir::x_60(args);	break;
        case 61: x_QDir::x_61(args);	break;
        case 62: x_QDir::x_62(args);	break;
        case 63: x_QDir::x_63(args);	break;
        case 64: x_QDir::x_64(args);	break;
        case 65: x_QDir::x_65(args);	break;
        case 66: x_QDir::x_66(args);	break;
        case 67: xself->x_67(args);	break;
        case 68: x_QDir::x_68(args);	break;
        case 69: x_QDir::x_69(args);	break;
        case 70: x_QDir::x_70(args);	break;
        case 71: xself->x_71(args);	break;
        case 72: xself->x_72(args);	break;
        case 73: xself->x_73(args);	break;
        case 74: xself->x_74(args);	break;
        case 75: xself->x_75(args);	break;
        case 76: xself->x_76(args);	break;
        case 77: xself->x_77(args);	break;
        case 78: xself->x_78(args);	break;
        case 79: x_QDir::x_79(args);	break;
        case 80: x_QDir::x_80(args);	break;
        case 81: x_QDir::x_81(args);	break;
        case 82: x_QDir::x_82(args);	break;
        case 83: x_QDir::x_83(args);	break;
        case 84: x_QDir::x_84(args);	break;
        case 85: x_QDir::x_85(args);	break;
        case 86: x_QDir::x_86(args);	break;
        case 87: x_QDir::x_87(args);	break;
        case 88: x_QDir::x_88(args);	break;
        case 89: x_QDir::x_89(args);	break;
        case 90: x_QDir::x_90(args);	break;
        case 91: x_QDir::x_91(args);	break;
        case 92: x_QDir::x_92(args);	break;
        case 93: x_QDir::x_93(args);	break;
        case 94: x_QDir::x_94(args);	break;
        case 95: x_QDir::x_95(args);	break;
        case 96: x_QDir::x_96(args);	break;
        case 97: x_QDir::x_97(args);	break;
        case 98: x_QDir::x_98(args);	break;
        case 99: x_QDir::x_99(args);	break;
        case 100: x_QDir::x_100(args);	break;
        case 101: x_QDir::x_101(args);	break;
        case 102: x_QDir::x_102(args);	break;
        case 103: x_QDir::x_103(args);	break;
        case 104: x_QDir::x_104(args);	break;
        case 105: x_QDir::x_105(args);	break;
        case 106: x_QDir::x_106(args);	break;
        case 107: x_QDir::x_107(args);	break;
        case 108: x_QDir::x_108(args);	break;
        case 109: x_QDir::x_109(args);	break;
        case 110: x_QDir::x_110(args);	break;
        case 111: delete (QDir*)xself;	break;
    }
}
class x_QDirIterator : public QDirIterator, public __internal_SmokeClass {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    static void x_1(Smoke::Stack x) {
        // QDirIterator* QDirIterator(const QDir&, QFlags<QDirIterator::IteratorFlag>)
        x_QDirIterator* xret = new x_QDirIterator(*(const QDir*)x[1].s_class,(QFlags<QDirIterator::IteratorFlag>)x[2].s_uint);
        x[0].s_class = (void*)xret;
    }
    explicit x_QDirIterator(const QDir& x1, QFlags<QDirIterator::IteratorFlag> x2) : QDirIterator(x1, x2) {}
    static void x_2(Smoke::Stack x) {
        // QDirIterator* QDirIterator(const QString&, QFlags<QDirIterator::IteratorFlag>)
        x_QDirIterator* xret = new x_QDirIterator(*(const QString*)x[1].s_class,(QFlags<QDirIterator::IteratorFlag>)x[2].s_uint);
        x[0].s_class = (void*)xret;
    }
    explicit x_QDirIterator(const QString& x1, QFlags<QDirIterator::IteratorFlag> x2) : QDirIterator(x1, x2) {}
    static void x_3(Smoke::Stack x) {
        // QDirIterator* QDirIterator(const QString&, QFlags<QDir::Filter>, QFlags<QDirIterator::IteratorFlag>)
        x_QDirIterator* xret = new x_QDirIterator(*(const QString*)x[1].s_class,(QFlags<QDir::Filter>)x[2].s_uint,(QFlags<QDirIterator::IteratorFlag>)x[3].s_uint);
        x[0].s_class = (void*)xret;
    }
    explicit x_QDirIterator(const QString& x1, QFlags<QDir::Filter> x2, QFlags<QDirIterator::IteratorFlag> x3) : QDirIterator(x1, x2, x3) {}
    static void x_4(Smoke::Stack x) {
        // QDirIterator* QDirIterator(const QString&, const QStringList&, QFlags<QDir::Filter>, QFlags<QDirIterator::IteratorFlag>)
        x_QDirIterator* xret = new x_QDirIterator(*(const QString*)x[1].s_class,*(const QStringList*)x[2].s_class,(QFlags<QDir::Filter>)x[3].s_uint,(QFlags<QDirIterator::IteratorFlag>)x[4].s_uint);
        x[0].s_class = (void*)xret;
    }
    explicit x_QDirIterator(const QString& x1, const QStringList& x2, QFlags<QDir::Filter> x3, QFlags<QDirIterator::IteratorFlag> x4) : QDirIterator(x1, x2, x3, x4) {}
    void x_5(Smoke::Stack x) {
        // QString next()
        QString xret = this->QDirIterator::next();
        x[0].s_class = (void*)new QString(xret);
    }
    void x_6(Smoke::Stack x) {
        // bool hasNext() const
        bool xret = ((const x_QDirIterator*)this)->QDirIterator::hasNext();
        x[0].s_bool = xret;
    }
    void x_7(Smoke::Stack x) {
        // QString fileName() const
        QString xret = ((const x_QDirIterator*)this)->QDirIterator::fileName();
        x[0].s_class = (void*)new QString(xret);
    }
    void x_8(Smoke::Stack x) {
        // QString filePath() const
        QString xret = ((const x_QDirIterator*)this)->QDirIterator::filePath();
        x[0].s_class = (void*)new QString(xret);
    }
    void x_9(Smoke::Stack x) {
        // QFileInfo fileInfo() const
        QFileInfo xret = ((const x_QDirIterator*)this)->QDirIterator::fileInfo();
        x[0].s_class = (void*)new QFileInfo(xret);
    }
    void x_10(Smoke::Stack x) {
        // QString path() const
        QString xret = ((const x_QDirIterator*)this)->QDirIterator::path();
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_11(Smoke::Stack x) {
        // QDirIterator* QDirIterator(const QDir&)
        x_QDirIterator* xret = new x_QDirIterator(*(const QDir*)x[1].s_class,(QFlags<QDirIterator::IteratorFlag>)QDirIterator::NoIteratorFlags);
        x[0].s_class = (void*)xret;
    }
    static void x_12(Smoke::Stack x) {
        // QDirIterator* QDirIterator(const QString&)
        x_QDirIterator* xret = new x_QDirIterator(*(const QString*)x[1].s_class,(QFlags<QDirIterator::IteratorFlag>)QDirIterator::NoIteratorFlags);
        x[0].s_class = (void*)xret;
    }
    static void x_13(Smoke::Stack x) {
        // QDirIterator* QDirIterator(const QString&, QFlags<QDir::Filter>)
        x_QDirIterator* xret = new x_QDirIterator(*(const QString*)x[1].s_class,(QFlags<QDir::Filter>)x[2].s_uint,(QFlags<QDirIterator::IteratorFlag>)QDirIterator::NoIteratorFlags);
        x[0].s_class = (void*)xret;
    }
    static void x_14(Smoke::Stack x) {
        // QDirIterator* QDirIterator(const QString&, const QStringList&)
        x_QDirIterator* xret = new x_QDirIterator(*(const QString*)x[1].s_class,*(const QStringList*)x[2].s_class,(QFlags<QDir::Filter>)QDir::NoFilter,(QFlags<QDirIterator::IteratorFlag>)QDirIterator::NoIteratorFlags);
        x[0].s_class = (void*)xret;
    }
    static void x_15(Smoke::Stack x) {
        // QDirIterator* QDirIterator(const QString&, const QStringList&, QFlags<QDir::Filter>)
        x_QDirIterator* xret = new x_QDirIterator(*(const QString*)x[1].s_class,*(const QStringList*)x[2].s_class,(QFlags<QDir::Filter>)x[3].s_uint,(QFlags<QDirIterator::IteratorFlag>)QDirIterator::NoIteratorFlags);
        x[0].s_class = (void*)xret;
    }
    static void x_16(Smoke::Stack x) {
        x[0].s_enum = (long)QDirIterator::NoIteratorFlags;
    }
    static void x_17(Smoke::Stack x) {
        x[0].s_enum = (long)QDirIterator::FollowSymlinks;
    }
    static void x_18(Smoke::Stack x) {
        x[0].s_enum = (long)QDirIterator::Subdirectories;
    }
    static void xenum_operation(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
        switch(xtype) {
        case 89: //QDirIterator::IteratorFlag
            switch(xop) {
                case Smoke::EnumNew:
                    xdata = (void*)new QDirIterator::IteratorFlag;
                    break;
                case Smoke::EnumDelete:
                    delete (QDirIterator::IteratorFlag*)xdata;
                    break;
                case Smoke::EnumFromLong:
                    *(QDirIterator::IteratorFlag*)xdata = (QDirIterator::IteratorFlag)xvalue;
                    break;
                case Smoke::EnumToLong:
                    xvalue = (long)*(QDirIterator::IteratorFlag*)xdata;
                    break;
            }
            break;
        }
    }
    ~x_QDirIterator() { this->_binding->deleted(37, (void*)this); }
};
void xenum_QDirIterator(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
    x_QDirIterator::xenum_operation(xop, xtype, xdata, xvalue);
}
void xcall_QDirIterator(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QDirIterator *xself = (x_QDirIterator*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: x_QDirIterator::x_1(args);	break;
        case 2: x_QDirIterator::x_2(args);	break;
        case 3: x_QDirIterator::x_3(args);	break;
        case 4: x_QDirIterator::x_4(args);	break;
        case 5: xself->x_5(args);	break;
        case 6: xself->x_6(args);	break;
        case 7: xself->x_7(args);	break;
        case 8: xself->x_8(args);	break;
        case 9: xself->x_9(args);	break;
        case 10: xself->x_10(args);	break;
        case 11: x_QDirIterator::x_11(args);	break;
        case 12: x_QDirIterator::x_12(args);	break;
        case 13: x_QDirIterator::x_13(args);	break;
        case 14: x_QDirIterator::x_14(args);	break;
        case 15: x_QDirIterator::x_15(args);	break;
        case 16: x_QDirIterator::x_16(args);	break;
        case 17: x_QDirIterator::x_17(args);	break;
        case 18: x_QDirIterator::x_18(args);	break;
        case 19: delete (QDirIterator*)xself;	break;
    }
}
class x_QDynamicPropertyChangeEvent : public QDynamicPropertyChangeEvent, public __internal_SmokeClass {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    static void x_1(Smoke::Stack x) {
        // QDynamicPropertyChangeEvent* QDynamicPropertyChangeEvent(const QByteArray&)
        x_QDynamicPropertyChangeEvent* xret = new x_QDynamicPropertyChangeEvent(*(const QByteArray*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QDynamicPropertyChangeEvent(const QByteArray& x1) : QDynamicPropertyChangeEvent(x1) {}
    void x_2(Smoke::Stack x) {
        // QByteArray propertyName() const
        QByteArray xret = ((const x_QDynamicPropertyChangeEvent*)this)->QDynamicPropertyChangeEvent::propertyName();
        x[0].s_class = (void*)new QByteArray(xret);
    }
    static void x_3(Smoke::Stack x) {
        // QDynamicPropertyChangeEvent* QDynamicPropertyChangeEvent(const QDynamicPropertyChangeEvent&)
        x_QDynamicPropertyChangeEvent* xret = new x_QDynamicPropertyChangeEvent(*(const QDynamicPropertyChangeEvent*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QDynamicPropertyChangeEvent(const QDynamicPropertyChangeEvent& x1) : QDynamicPropertyChangeEvent(x1) {}
    ~x_QDynamicPropertyChangeEvent() { this->_binding->deleted(38, (void*)this); }
};
void xcall_QDynamicPropertyChangeEvent(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QDynamicPropertyChangeEvent *xself = (x_QDynamicPropertyChangeEvent*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: x_QDynamicPropertyChangeEvent::x_1(args);	break;
        case 2: xself->x_2(args);	break;
        case 3: x_QDynamicPropertyChangeEvent::x_3(args);	break;
        case 4: delete (QDynamicPropertyChangeEvent*)xself;	break;
    }
}
class x_QEasingCurve : public QEasingCurve {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    static void x_1(Smoke::Stack x) {
        // QEasingCurve* QEasingCurve(QEasingCurve::Type)
        x_QEasingCurve* xret = new x_QEasingCurve((QEasingCurve::Type)x[1].s_enum);
        x[0].s_class = (void*)xret;
    }
    explicit x_QEasingCurve(QEasingCurve::Type x1) : QEasingCurve(x1) {}
    static void x_2(Smoke::Stack x) {
        // QEasingCurve* QEasingCurve(const QEasingCurve&)
        x_QEasingCurve* xret = new x_QEasingCurve(*(const QEasingCurve*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QEasingCurve(const QEasingCurve& x1) : QEasingCurve(x1) {}
    void x_3(Smoke::Stack x) {
        // QEasingCurve& operator=(const QEasingCurve&)
        QEasingCurve& xret = this->QEasingCurve::operator=(*(const QEasingCurve*)x[1].s_class);
        x[0].s_class = (void*)&xret;
    }
    void x_4(Smoke::Stack x) {
        // bool operator==(const QEasingCurve&) const
        bool xret = ((const x_QEasingCurve*)this)->QEasingCurve::operator==(*(const QEasingCurve*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_5(Smoke::Stack x) {
        // bool operator!=(const QEasingCurve&) const
        bool xret = ((const x_QEasingCurve*)this)->QEasingCurve::operator!=(*(const QEasingCurve*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_6(Smoke::Stack x) {
        // double amplitude() const
        double xret = ((const x_QEasingCurve*)this)->QEasingCurve::amplitude();
        x[0].s_double = xret;
    }
    void x_7(Smoke::Stack x) {
        // void setAmplitude(double)
        this->QEasingCurve::setAmplitude((double)x[1].s_double);
        (void)x; // noop (for compiler warning)
    }
    void x_8(Smoke::Stack x) {
        // double period() const
        double xret = ((const x_QEasingCurve*)this)->QEasingCurve::period();
        x[0].s_double = xret;
    }
    void x_9(Smoke::Stack x) {
        // void setPeriod(double)
        this->QEasingCurve::setPeriod((double)x[1].s_double);
        (void)x; // noop (for compiler warning)
    }
    void x_10(Smoke::Stack x) {
        // double overshoot() const
        double xret = ((const x_QEasingCurve*)this)->QEasingCurve::overshoot();
        x[0].s_double = xret;
    }
    void x_11(Smoke::Stack x) {
        // void setOvershoot(double)
        this->QEasingCurve::setOvershoot((double)x[1].s_double);
        (void)x; // noop (for compiler warning)
    }
    void x_12(Smoke::Stack x) {
        // QEasingCurve::Type type() const
        QEasingCurve::Type xret = ((const x_QEasingCurve*)this)->QEasingCurve::type();
        x[0].s_enum = xret;
    }
    void x_13(Smoke::Stack x) {
        // void setType(QEasingCurve::Type)
        this->QEasingCurve::setType((QEasingCurve::Type)x[1].s_enum);
        (void)x; // noop (for compiler warning)
    }
    void x_14(Smoke::Stack x) {
        // void setCustomType(double(*)(double))
        this->QEasingCurve::setCustomType((double(*)(double))x[1].s_class);
        (void)x; // noop (for compiler warning)
    }
    void x_15(Smoke::Stack x) {
        // double(*)(double) customType() const
        double(*xret)(double) = ((const x_QEasingCurve*)this)->QEasingCurve::customType();
        x[0].s_class = (void*)xret;
    }
    void x_16(Smoke::Stack x) {
        // double valueForProgress(double) const
        double xret = ((const x_QEasingCurve*)this)->QEasingCurve::valueForProgress((double)x[1].s_double);
        x[0].s_double = xret;
    }
    static void x_17(Smoke::Stack x) {
        // QEasingCurve* QEasingCurve()
        x_QEasingCurve* xret = new x_QEasingCurve((QEasingCurve::Type)QEasingCurve::Linear);
        x[0].s_class = (void*)xret;
    }
    static void x_18(Smoke::Stack x) {
        // static const QMetaObject staticMetaObject
        x[0].s_class = (void*)&QEasingCurve::staticMetaObject;
    }
    static void x_19(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::Linear;
    }
    static void x_20(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InQuad;
    }
    static void x_21(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutQuad;
    }
    static void x_22(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InOutQuad;
    }
    static void x_23(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutInQuad;
    }
    static void x_24(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InCubic;
    }
    static void x_25(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutCubic;
    }
    static void x_26(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InOutCubic;
    }
    static void x_27(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutInCubic;
    }
    static void x_28(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InQuart;
    }
    static void x_29(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutQuart;
    }
    static void x_30(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InOutQuart;
    }
    static void x_31(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutInQuart;
    }
    static void x_32(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InQuint;
    }
    static void x_33(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutQuint;
    }
    static void x_34(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InOutQuint;
    }
    static void x_35(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutInQuint;
    }
    static void x_36(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InSine;
    }
    static void x_37(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutSine;
    }
    static void x_38(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InOutSine;
    }
    static void x_39(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutInSine;
    }
    static void x_40(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InExpo;
    }
    static void x_41(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutExpo;
    }
    static void x_42(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InOutExpo;
    }
    static void x_43(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutInExpo;
    }
    static void x_44(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InCirc;
    }
    static void x_45(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutCirc;
    }
    static void x_46(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InOutCirc;
    }
    static void x_47(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutInCirc;
    }
    static void x_48(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InElastic;
    }
    static void x_49(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutElastic;
    }
    static void x_50(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InOutElastic;
    }
    static void x_51(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutInElastic;
    }
    static void x_52(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InBack;
    }
    static void x_53(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutBack;
    }
    static void x_54(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InOutBack;
    }
    static void x_55(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutInBack;
    }
    static void x_56(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InBounce;
    }
    static void x_57(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutBounce;
    }
    static void x_58(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InOutBounce;
    }
    static void x_59(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutInBounce;
    }
    static void x_60(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::InCurve;
    }
    static void x_61(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::OutCurve;
    }
    static void x_62(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::SineCurve;
    }
    static void x_63(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::CosineCurve;
    }
    static void x_64(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::Custom;
    }
    static void x_65(Smoke::Stack x) {
        x[0].s_enum = (long)QEasingCurve::NCurveTypes;
    }
    static void xenum_operation(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
        switch(xtype) {
        case 94: //QEasingCurve::Type
            switch(xop) {
                case Smoke::EnumNew:
                    xdata = (void*)new QEasingCurve::Type;
                    break;
                case Smoke::EnumDelete:
                    delete (QEasingCurve::Type*)xdata;
                    break;
                case Smoke::EnumFromLong:
                    *(QEasingCurve::Type*)xdata = (QEasingCurve::Type)xvalue;
                    break;
                case Smoke::EnumToLong:
                    xvalue = (long)*(QEasingCurve::Type*)xdata;
                    break;
            }
            break;
        }
    }
    ~x_QEasingCurve() { this->_binding->deleted(39, (void*)this); }
};
void xenum_QEasingCurve(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
    x_QEasingCurve::xenum_operation(xop, xtype, xdata, xvalue);
}
void xcall_QEasingCurve(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QEasingCurve *xself = (x_QEasingCurve*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: x_QEasingCurve::x_1(args);	break;
        case 2: x_QEasingCurve::x_2(args);	break;
        case 3: xself->x_3(args);	break;
        case 4: xself->x_4(args);	break;
        case 5: xself->x_5(args);	break;
        case 6: xself->x_6(args);	break;
        case 7: xself->x_7(args);	break;
        case 8: xself->x_8(args);	break;
        case 9: xself->x_9(args);	break;
        case 10: xself->x_10(args);	break;
        case 11: xself->x_11(args);	break;
        case 12: xself->x_12(args);	break;
        case 13: xself->x_13(args);	break;
        case 14: xself->x_14(args);	break;
        case 15: xself->x_15(args);	break;
        case 16: xself->x_16(args);	break;
        case 17: x_QEasingCurve::x_17(args);	break;
        case 18: x_QEasingCurve::x_18(args);	break;
        case 19: x_QEasingCurve::x_19(args);	break;
        case 20: x_QEasingCurve::x_20(args);	break;
        case 21: x_QEasingCurve::x_21(args);	break;
        case 22: x_QEasingCurve::x_22(args);	break;
        case 23: x_QEasingCurve::x_23(args);	break;
        case 24: x_QEasingCurve::x_24(args);	break;
        case 25: x_QEasingCurve::x_25(args);	break;
        case 26: x_QEasingCurve::x_26(args);	break;
        case 27: x_QEasingCurve::x_27(args);	break;
        case 28: x_QEasingCurve::x_28(args);	break;
        case 29: x_QEasingCurve::x_29(args);	break;
        case 30: x_QEasingCurve::x_30(args);	break;
        case 31: x_QEasingCurve::x_31(args);	break;
        case 32: x_QEasingCurve::x_32(args);	break;
        case 33: x_QEasingCurve::x_33(args);	break;
        case 34: x_QEasingCurve::x_34(args);	break;
        case 35: x_QEasingCurve::x_35(args);	break;
        case 36: x_QEasingCurve::x_36(args);	break;
        case 37: x_QEasingCurve::x_37(args);	break;
        case 38: x_QEasingCurve::x_38(args);	break;
        case 39: x_QEasingCurve::x_39(args);	break;
        case 40: x_QEasingCurve::x_40(args);	break;
        case 41: x_QEasingCurve::x_41(args);	break;
        case 42: x_QEasingCurve::x_42(args);	break;
        case 43: x_QEasingCurve::x_43(args);	break;
        case 44: x_QEasingCurve::x_44(args);	break;
        case 45: x_QEasingCurve::x_45(args);	break;
        case 46: x_QEasingCurve::x_46(args);	break;
        case 47: x_QEasingCurve::x_47(args);	break;
        case 48: x_QEasingCurve::x_48(args);	break;
        case 49: x_QEasingCurve::x_49(args);	break;
        case 50: x_QEasingCurve::x_50(args);	break;
        case 51: x_QEasingCurve::x_51(args);	break;
        case 52: x_QEasingCurve::x_52(args);	break;
        case 53: x_QEasingCurve::x_53(args);	break;
        case 54: x_QEasingCurve::x_54(args);	break;
        case 55: x_QEasingCurve::x_55(args);	break;
        case 56: x_QEasingCurve::x_56(args);	break;
        case 57: x_QEasingCurve::x_57(args);	break;
        case 58: x_QEasingCurve::x_58(args);	break;
        case 59: x_QEasingCurve::x_59(args);	break;
        case 60: x_QEasingCurve::x_60(args);	break;
        case 61: x_QEasingCurve::x_61(args);	break;
        case 62: x_QEasingCurve::x_62(args);	break;
        case 63: x_QEasingCurve::x_63(args);	break;
        case 64: x_QEasingCurve::x_64(args);	break;
        case 65: x_QEasingCurve::x_65(args);	break;
        case 66: delete (QEasingCurve*)xself;	break;
    }
}
class x_QElapsedTimer : public QElapsedTimer {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    static void x_1(Smoke::Stack x) {
        // static QElapsedTimer::ClockType clockType()
        QElapsedTimer::ClockType xret = QElapsedTimer::clockType();
        x[0].s_enum = xret;
    }
    static void x_2(Smoke::Stack x) {
        // static bool isMonotonic()
        bool xret = QElapsedTimer::isMonotonic();
        x[0].s_bool = xret;
    }
    void x_3(Smoke::Stack x) {
        // void start()
        this->QElapsedTimer::start();
        (void)x; // noop (for compiler warning)
    }
    void x_4(Smoke::Stack x) {
        // long long restart()
        long long xret = this->QElapsedTimer::restart();
        x[0].s_class = (void*)new long long(xret);
    }
    void x_5(Smoke::Stack x) {
        // void invalidate()
        this->QElapsedTimer::invalidate();
        (void)x; // noop (for compiler warning)
    }
    void x_6(Smoke::Stack x) {
        // bool isValid() const
        bool xret = ((const x_QElapsedTimer*)this)->QElapsedTimer::isValid();
        x[0].s_bool = xret;
    }
    void x_7(Smoke::Stack x) {
        // long long nsecsElapsed() const
        long long xret = ((const x_QElapsedTimer*)this)->QElapsedTimer::nsecsElapsed();
        x[0].s_class = (void*)new long long(xret);
    }
    void x_8(Smoke::Stack x) {
        // long long elapsed() const
        long long xret = ((const x_QElapsedTimer*)this)->QElapsedTimer::elapsed();
        x[0].s_class = (void*)new long long(xret);
    }
    void x_9(Smoke::Stack x) {
        // bool hasExpired(long long) const
        bool xret = ((const x_QElapsedTimer*)this)->QElapsedTimer::hasExpired(*(long long*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_10(Smoke::Stack x) {
        // long long msecsSinceReference() const
        long long xret = ((const x_QElapsedTimer*)this)->QElapsedTimer::msecsSinceReference();
        x[0].s_class = (void*)new long long(xret);
    }
    void x_11(Smoke::Stack x) {
        // long long msecsTo(const QElapsedTimer&) const
        long long xret = ((const x_QElapsedTimer*)this)->QElapsedTimer::msecsTo(*(const QElapsedTimer*)x[1].s_class);
        x[0].s_class = (void*)new long long(xret);
    }
    void x_12(Smoke::Stack x) {
        // long long secsTo(const QElapsedTimer&) const
        long long xret = ((const x_QElapsedTimer*)this)->QElapsedTimer::secsTo(*(const QElapsedTimer*)x[1].s_class);
        x[0].s_class = (void*)new long long(xret);
    }
    void x_13(Smoke::Stack x) {
        // bool operator==(const QElapsedTimer&) const
        bool xret = ((const x_QElapsedTimer*)this)->QElapsedTimer::operator==(*(const QElapsedTimer*)x[1].s_class);
        x[0].s_bool = xret;
    }
    void x_14(Smoke::Stack x) {
        // bool operator!=(const QElapsedTimer&) const
        bool xret = ((const x_QElapsedTimer*)this)->QElapsedTimer::operator!=(*(const QElapsedTimer*)x[1].s_class);
        x[0].s_bool = xret;
    }
    static void x_15(Smoke::Stack x) {
        // QElapsedTimer* QElapsedTimer()
        x_QElapsedTimer* xret = new x_QElapsedTimer();
        x[0].s_class = (void*)xret;
    }
    explicit x_QElapsedTimer() : QElapsedTimer() {}
    static void x_16(Smoke::Stack x) {
        // QElapsedTimer* QElapsedTimer(const QElapsedTimer&)
        x_QElapsedTimer* xret = new x_QElapsedTimer(*(const QElapsedTimer*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QElapsedTimer(const QElapsedTimer& x1) : QElapsedTimer(x1) {}
    static void x_17(Smoke::Stack x) {
        x[0].s_enum = (long)QElapsedTimer::SystemTime;
    }
    static void x_18(Smoke::Stack x) {
        x[0].s_enum = (long)QElapsedTimer::MonotonicClock;
    }
    static void x_19(Smoke::Stack x) {
        x[0].s_enum = (long)QElapsedTimer::TickCounter;
    }
    static void x_20(Smoke::Stack x) {
        x[0].s_enum = (long)QElapsedTimer::MachAbsoluteTime;
    }
    static void x_21(Smoke::Stack x) {
        x[0].s_enum = (long)QElapsedTimer::PerformanceCounter;
    }
    static void xenum_operation(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
        switch(xtype) {
        case 96: //QElapsedTimer::ClockType
            switch(xop) {
                case Smoke::EnumNew:
                    xdata = (void*)new QElapsedTimer::ClockType;
                    break;
                case Smoke::EnumDelete:
                    delete (QElapsedTimer::ClockType*)xdata;
                    break;
                case Smoke::EnumFromLong:
                    *(QElapsedTimer::ClockType*)xdata = (QElapsedTimer::ClockType)xvalue;
                    break;
                case Smoke::EnumToLong:
                    xvalue = (long)*(QElapsedTimer::ClockType*)xdata;
                    break;
            }
            break;
        }
    }
    ~x_QElapsedTimer() { this->_binding->deleted(40, (void*)this); }
};
void xenum_QElapsedTimer(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
    x_QElapsedTimer::xenum_operation(xop, xtype, xdata, xvalue);
}
void xcall_QElapsedTimer(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QElapsedTimer *xself = (x_QElapsedTimer*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: x_QElapsedTimer::x_1(args);	break;
        case 2: x_QElapsedTimer::x_2(args);	break;
        case 3: xself->x_3(args);	break;
        case 4: xself->x_4(args);	break;
        case 5: xself->x_5(args);	break;
        case 6: xself->x_6(args);	break;
        case 7: xself->x_7(args);	break;
        case 8: xself->x_8(args);	break;
        case 9: xself->x_9(args);	break;
        case 10: xself->x_10(args);	break;
        case 11: xself->x_11(args);	break;
        case 12: xself->x_12(args);	break;
        case 13: xself->x_13(args);	break;
        case 14: xself->x_14(args);	break;
        case 15: x_QElapsedTimer::x_15(args);	break;
        case 16: x_QElapsedTimer::x_16(args);	break;
        case 17: x_QElapsedTimer::x_17(args);	break;
        case 18: x_QElapsedTimer::x_18(args);	break;
        case 19: x_QElapsedTimer::x_19(args);	break;
        case 20: x_QElapsedTimer::x_20(args);	break;
        case 21: x_QElapsedTimer::x_21(args);	break;
        case 22: delete (QElapsedTimer*)xself;	break;
    }
}
class x_QEvent : public QEvent, public __internal_SmokeClass {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    static void x_1(Smoke::Stack x) {
        // QEvent* QEvent(QEvent::Type)
        x_QEvent* xret = new x_QEvent((QEvent::Type)x[1].s_enum);
        x[0].s_class = (void*)xret;
    }
    explicit x_QEvent(QEvent::Type x1) : QEvent(x1) {}
    void x_2(Smoke::Stack x) {
        // QEvent::Type type() const
        QEvent::Type xret = ((const x_QEvent*)this)->QEvent::type();
        x[0].s_enum = xret;
    }
    void x_3(Smoke::Stack x) {
        // bool spontaneous() const
        bool xret = ((const x_QEvent*)this)->QEvent::spontaneous();
        x[0].s_bool = xret;
    }
    void x_4(Smoke::Stack x) {
        // void setAccepted(bool)
        this->QEvent::setAccepted((bool)x[1].s_bool);
        (void)x; // noop (for compiler warning)
    }
    void x_5(Smoke::Stack x) {
        // bool isAccepted() const
        bool xret = ((const x_QEvent*)this)->QEvent::isAccepted();
        x[0].s_bool = xret;
    }
    void x_6(Smoke::Stack x) {
        // void accept()
        this->QEvent::accept();
        (void)x; // noop (for compiler warning)
    }
    void x_7(Smoke::Stack x) {
        // void ignore()
        this->QEvent::ignore();
        (void)x; // noop (for compiler warning)
    }
    static void x_8(Smoke::Stack x) {
        // static int registerEventType(int)
        int xret = QEvent::registerEventType((int)x[1].s_int);
        x[0].s_int = xret;
    }
    static void x_9(Smoke::Stack x) {
        // QEvent* QEvent(const QEvent&)
        x_QEvent* xret = new x_QEvent(*(const QEvent*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QEvent(const QEvent& x1) : QEvent(x1) {}
    static void x_10(Smoke::Stack x) {
        // static int registerEventType()
        int xret = QEvent::registerEventType((int)-1);
        x[0].s_int = xret;
    }
    static void x_11(Smoke::Stack x) {
        // static const QMetaObject staticMetaObject
        x[0].s_class = (void*)&QEvent::staticMetaObject;
    }
    void x_12(Smoke::Stack x) {
        // QEventPrivate* d
        x[0].s_class = (void*)this->QEvent::d;
    }
    void x_13(Smoke::Stack x) {
        // QEventPrivate* d=
        this->QEvent::d = (QEventPrivate*)x[1].s_class;
    }
    void x_14(Smoke::Stack x) {
        // unsigned short t
        x[0].s_ushort = this->QEvent::t;
    }
    void x_15(Smoke::Stack x) {
        // unsigned short t=
        this->QEvent::t = (unsigned short)x[1].s_ushort;
    }
    static void x_16(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::None;
    }
    static void x_17(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Timer;
    }
    static void x_18(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::MouseButtonPress;
    }
    static void x_19(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::MouseButtonRelease;
    }
    static void x_20(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::MouseButtonDblClick;
    }
    static void x_21(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::MouseMove;
    }
    static void x_22(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::KeyPress;
    }
    static void x_23(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::KeyRelease;
    }
    static void x_24(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::FocusIn;
    }
    static void x_25(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::FocusOut;
    }
    static void x_26(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Enter;
    }
    static void x_27(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Leave;
    }
    static void x_28(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Paint;
    }
    static void x_29(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Move;
    }
    static void x_30(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Resize;
    }
    static void x_31(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Create;
    }
    static void x_32(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Destroy;
    }
    static void x_33(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Show;
    }
    static void x_34(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Hide;
    }
    static void x_35(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Close;
    }
    static void x_36(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Quit;
    }
    static void x_37(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ParentChange;
    }
    static void x_38(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ParentAboutToChange;
    }
    static void x_39(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ThreadChange;
    }
    static void x_40(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::WindowActivate;
    }
    static void x_41(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::WindowDeactivate;
    }
    static void x_42(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ShowToParent;
    }
    static void x_43(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::HideToParent;
    }
    static void x_44(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Wheel;
    }
    static void x_45(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::WindowTitleChange;
    }
    static void x_46(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::WindowIconChange;
    }
    static void x_47(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ApplicationWindowIconChange;
    }
    static void x_48(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ApplicationFontChange;
    }
    static void x_49(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ApplicationLayoutDirectionChange;
    }
    static void x_50(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ApplicationPaletteChange;
    }
    static void x_51(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::PaletteChange;
    }
    static void x_52(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Clipboard;
    }
    static void x_53(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Speech;
    }
    static void x_54(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::MetaCall;
    }
    static void x_55(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::SockAct;
    }
    static void x_56(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::WinEventAct;
    }
    static void x_57(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::DeferredDelete;
    }
    static void x_58(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::DragEnter;
    }
    static void x_59(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::DragMove;
    }
    static void x_60(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::DragLeave;
    }
    static void x_61(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Drop;
    }
    static void x_62(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::DragResponse;
    }
    static void x_63(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ChildAdded;
    }
    static void x_64(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ChildPolished;
    }
    static void x_65(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ChildRemoved;
    }
    static void x_66(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ShowWindowRequest;
    }
    static void x_67(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::PolishRequest;
    }
    static void x_68(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Polish;
    }
    static void x_69(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::LayoutRequest;
    }
    static void x_70(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::UpdateRequest;
    }
    static void x_71(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::UpdateLater;
    }
    static void x_72(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::EmbeddingControl;
    }
    static void x_73(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ActivateControl;
    }
    static void x_74(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::DeactivateControl;
    }
    static void x_75(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ContextMenu;
    }
    static void x_76(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::InputMethod;
    }
    static void x_77(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::AccessibilityPrepare;
    }
    static void x_78(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::TabletMove;
    }
    static void x_79(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::LocaleChange;
    }
    static void x_80(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::LanguageChange;
    }
    static void x_81(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::LayoutDirectionChange;
    }
    static void x_82(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Style;
    }
    static void x_83(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::TabletPress;
    }
    static void x_84(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::TabletRelease;
    }
    static void x_85(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::OkRequest;
    }
    static void x_86(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::HelpRequest;
    }
    static void x_87(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::IconDrag;
    }
    static void x_88(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::FontChange;
    }
    static void x_89(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::EnabledChange;
    }
    static void x_90(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ActivationChange;
    }
    static void x_91(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::StyleChange;
    }
    static void x_92(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::IconTextChange;
    }
    static void x_93(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ModifiedChange;
    }
    static void x_94(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::MouseTrackingChange;
    }
    static void x_95(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::WindowBlocked;
    }
    static void x_96(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::WindowUnblocked;
    }
    static void x_97(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::WindowStateChange;
    }
    static void x_98(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ToolTip;
    }
    static void x_99(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::WhatsThis;
    }
    static void x_100(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::StatusTip;
    }
    static void x_101(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ActionChanged;
    }
    static void x_102(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ActionAdded;
    }
    static void x_103(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ActionRemoved;
    }
    static void x_104(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::FileOpen;
    }
    static void x_105(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Shortcut;
    }
    static void x_106(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ShortcutOverride;
    }
    static void x_107(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::WhatsThisClicked;
    }
    static void x_108(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ToolBarChange;
    }
    static void x_109(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ApplicationActivate;
    }
    static void x_110(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ApplicationActivated;
    }
    static void x_111(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ApplicationDeactivate;
    }
    static void x_112(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ApplicationDeactivated;
    }
    static void x_113(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::QueryWhatsThis;
    }
    static void x_114(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::EnterWhatsThisMode;
    }
    static void x_115(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::LeaveWhatsThisMode;
    }
    static void x_116(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ZOrderChange;
    }
    static void x_117(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::HoverEnter;
    }
    static void x_118(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::HoverLeave;
    }
    static void x_119(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::HoverMove;
    }
    static void x_120(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::AccessibilityHelp;
    }
    static void x_121(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::AccessibilityDescription;
    }
    static void x_122(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::AcceptDropsChange;
    }
    static void x_123(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::MenubarUpdated;
    }
    static void x_124(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ZeroTimerEvent;
    }
    static void x_125(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneMouseMove;
    }
    static void x_126(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneMousePress;
    }
    static void x_127(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneMouseRelease;
    }
    static void x_128(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneMouseDoubleClick;
    }
    static void x_129(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneContextMenu;
    }
    static void x_130(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneHoverEnter;
    }
    static void x_131(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneHoverMove;
    }
    static void x_132(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneHoverLeave;
    }
    static void x_133(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneHelp;
    }
    static void x_134(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneDragEnter;
    }
    static void x_135(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneDragMove;
    }
    static void x_136(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneDragLeave;
    }
    static void x_137(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneDrop;
    }
    static void x_138(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneWheel;
    }
    static void x_139(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::KeyboardLayoutChange;
    }
    static void x_140(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::DynamicPropertyChange;
    }
    static void x_141(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::TabletEnterProximity;
    }
    static void x_142(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::TabletLeaveProximity;
    }
    static void x_143(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::NonClientAreaMouseMove;
    }
    static void x_144(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::NonClientAreaMouseButtonPress;
    }
    static void x_145(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::NonClientAreaMouseButtonRelease;
    }
    static void x_146(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::NonClientAreaMouseButtonDblClick;
    }
    static void x_147(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::MacSizeChange;
    }
    static void x_148(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ContentsRectChange;
    }
    static void x_149(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::MacGLWindowChange;
    }
    static void x_150(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::FutureCallOut;
    }
    static void x_151(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneResize;
    }
    static void x_152(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GraphicsSceneMove;
    }
    static void x_153(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::CursorChange;
    }
    static void x_154(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::ToolTipChange;
    }
    static void x_155(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::NetworkReplyUpdated;
    }
    static void x_156(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GrabMouse;
    }
    static void x_157(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::UngrabMouse;
    }
    static void x_158(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GrabKeyboard;
    }
    static void x_159(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::UngrabKeyboard;
    }
    static void x_160(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::MacGLClearDrawable;
    }
    static void x_161(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::StateMachineSignal;
    }
    static void x_162(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::StateMachineWrapped;
    }
    static void x_163(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::TouchBegin;
    }
    static void x_164(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::TouchUpdate;
    }
    static void x_165(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::TouchEnd;
    }
    static void x_166(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::NativeGesture;
    }
    static void x_167(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::RequestSoftwareInputPanel;
    }
    static void x_168(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::CloseSoftwareInputPanel;
    }
    static void x_169(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::UpdateSoftKeys;
    }
    static void x_170(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::WinIdChange;
    }
    static void x_171(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::Gesture;
    }
    static void x_172(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::GestureOverride;
    }
    static void x_173(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::PlatformPanel;
    }
    static void x_174(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::User;
    }
    static void x_175(Smoke::Stack x) {
        x[0].s_enum = (long)QEvent::MaxUser;
    }
    static void xenum_operation(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
        switch(xtype) {
        case 98: //QEvent::Type
            switch(xop) {
                case Smoke::EnumNew:
                    xdata = (void*)new QEvent::Type;
                    break;
                case Smoke::EnumDelete:
                    delete (QEvent::Type*)xdata;
                    break;
                case Smoke::EnumFromLong:
                    *(QEvent::Type*)xdata = (QEvent::Type)xvalue;
                    break;
                case Smoke::EnumToLong:
                    xvalue = (long)*(QEvent::Type*)xdata;
                    break;
            }
            break;
        }
    }
    ~x_QEvent() { this->_binding->deleted(41, (void*)this); }
};
void xenum_QEvent(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
    x_QEvent::xenum_operation(xop, xtype, xdata, xvalue);
}
void xcall_QEvent(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QEvent *xself = (x_QEvent*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: x_QEvent::x_1(args);	break;
        case 2: xself->x_2(args);	break;
        case 3: xself->x_3(args);	break;
        case 4: xself->x_4(args);	break;
        case 5: xself->x_5(args);	break;
        case 6: xself->x_6(args);	break;
        case 7: xself->x_7(args);	break;
        case 8: x_QEvent::x_8(args);	break;
        case 9: x_QEvent::x_9(args);	break;
        case 10: x_QEvent::x_10(args);	break;
        case 11: x_QEvent::x_11(args);	break;
        case 12: xself->x_12(args);	break;
        case 13: xself->x_13(args);	break;
        case 14: xself->x_14(args);	break;
        case 15: xself->x_15(args);	break;
        case 16: x_QEvent::x_16(args);	break;
        case 17: x_QEvent::x_17(args);	break;
        case 18: x_QEvent::x_18(args);	break;
        case 19: x_QEvent::x_19(args);	break;
        case 20: x_QEvent::x_20(args);	break;
        case 21: x_QEvent::x_21(args);	break;
        case 22: x_QEvent::x_22(args);	break;
        case 23: x_QEvent::x_23(args);	break;
        case 24: x_QEvent::x_24(args);	break;
        case 25: x_QEvent::x_25(args);	break;
        case 26: x_QEvent::x_26(args);	break;
        case 27: x_QEvent::x_27(args);	break;
        case 28: x_QEvent::x_28(args);	break;
        case 29: x_QEvent::x_29(args);	break;
        case 30: x_QEvent::x_30(args);	break;
        case 31: x_QEvent::x_31(args);	break;
        case 32: x_QEvent::x_32(args);	break;
        case 33: x_QEvent::x_33(args);	break;
        case 34: x_QEvent::x_34(args);	break;
        case 35: x_QEvent::x_35(args);	break;
        case 36: x_QEvent::x_36(args);	break;
        case 37: x_QEvent::x_37(args);	break;
        case 38: x_QEvent::x_38(args);	break;
        case 39: x_QEvent::x_39(args);	break;
        case 40: x_QEvent::x_40(args);	break;
        case 41: x_QEvent::x_41(args);	break;
        case 42: x_QEvent::x_42(args);	break;
        case 43: x_QEvent::x_43(args);	break;
        case 44: x_QEvent::x_44(args);	break;
        case 45: x_QEvent::x_45(args);	break;
        case 46: x_QEvent::x_46(args);	break;
        case 47: x_QEvent::x_47(args);	break;
        case 48: x_QEvent::x_48(args);	break;
        case 49: x_QEvent::x_49(args);	break;
        case 50: x_QEvent::x_50(args);	break;
        case 51: x_QEvent::x_51(args);	break;
        case 52: x_QEvent::x_52(args);	break;
        case 53: x_QEvent::x_53(args);	break;
        case 54: x_QEvent::x_54(args);	break;
        case 55: x_QEvent::x_55(args);	break;
        case 56: x_QEvent::x_56(args);	break;
        case 57: x_QEvent::x_57(args);	break;
        case 58: x_QEvent::x_58(args);	break;
        case 59: x_QEvent::x_59(args);	break;
        case 60: x_QEvent::x_60(args);	break;
        case 61: x_QEvent::x_61(args);	break;
        case 62: x_QEvent::x_62(args);	break;
        case 63: x_QEvent::x_63(args);	break;
        case 64: x_QEvent::x_64(args);	break;
        case 65: x_QEvent::x_65(args);	break;
        case 66: x_QEvent::x_66(args);	break;
        case 67: x_QEvent::x_67(args);	break;
        case 68: x_QEvent::x_68(args);	break;
        case 69: x_QEvent::x_69(args);	break;
        case 70: x_QEvent::x_70(args);	break;
        case 71: x_QEvent::x_71(args);	break;
        case 72: x_QEvent::x_72(args);	break;
        case 73: x_QEvent::x_73(args);	break;
        case 74: x_QEvent::x_74(args);	break;
        case 75: x_QEvent::x_75(args);	break;
        case 76: x_QEvent::x_76(args);	break;
        case 77: x_QEvent::x_77(args);	break;
        case 78: x_QEvent::x_78(args);	break;
        case 79: x_QEvent::x_79(args);	break;
        case 80: x_QEvent::x_80(args);	break;
        case 81: x_QEvent::x_81(args);	break;
        case 82: x_QEvent::x_82(args);	break;
        case 83: x_QEvent::x_83(args);	break;
        case 84: x_QEvent::x_84(args);	break;
        case 85: x_QEvent::x_85(args);	break;
        case 86: x_QEvent::x_86(args);	break;
        case 87: x_QEvent::x_87(args);	break;
        case 88: x_QEvent::x_88(args);	break;
        case 89: x_QEvent::x_89(args);	break;
        case 90: x_QEvent::x_90(args);	break;
        case 91: x_QEvent::x_91(args);	break;
        case 92: x_QEvent::x_92(args);	break;
        case 93: x_QEvent::x_93(args);	break;
        case 94: x_QEvent::x_94(args);	break;
        case 95: x_QEvent::x_95(args);	break;
        case 96: x_QEvent::x_96(args);	break;
        case 97: x_QEvent::x_97(args);	break;
        case 98: x_QEvent::x_98(args);	break;
        case 99: x_QEvent::x_99(args);	break;
        case 100: x_QEvent::x_100(args);	break;
        case 101: x_QEvent::x_101(args);	break;
        case 102: x_QEvent::x_102(args);	break;
        case 103: x_QEvent::x_103(args);	break;
        case 104: x_QEvent::x_104(args);	break;
        case 105: x_QEvent::x_105(args);	break;
        case 106: x_QEvent::x_106(args);	break;
        case 107: x_QEvent::x_107(args);	break;
        case 108: x_QEvent::x_108(args);	break;
        case 109: x_QEvent::x_109(args);	break;
        case 110: x_QEvent::x_110(args);	break;
        case 111: x_QEvent::x_111(args);	break;
        case 112: x_QEvent::x_112(args);	break;
        case 113: x_QEvent::x_113(args);	break;
        case 114: x_QEvent::x_114(args);	break;
        case 115: x_QEvent::x_115(args);	break;
        case 116: x_QEvent::x_116(args);	break;
        case 117: x_QEvent::x_117(args);	break;
        case 118: x_QEvent::x_118(args);	break;
        case 119: x_QEvent::x_119(args);	break;
        case 120: x_QEvent::x_120(args);	break;
        case 121: x_QEvent::x_121(args);	break;
        case 122: x_QEvent::x_122(args);	break;
        case 123: x_QEvent::x_123(args);	break;
        case 124: x_QEvent::x_124(args);	break;
        case 125: x_QEvent::x_125(args);	break;
        case 126: x_QEvent::x_126(args);	break;
        case 127: x_QEvent::x_127(args);	break;
        case 128: x_QEvent::x_128(args);	break;
        case 129: x_QEvent::x_129(args);	break;
        case 130: x_QEvent::x_130(args);	break;
        case 131: x_QEvent::x_131(args);	break;
        case 132: x_QEvent::x_132(args);	break;
        case 133: x_QEvent::x_133(args);	break;
        case 134: x_QEvent::x_134(args);	break;
        case 135: x_QEvent::x_135(args);	break;
        case 136: x_QEvent::x_136(args);	break;
        case 137: x_QEvent::x_137(args);	break;
        case 138: x_QEvent::x_138(args);	break;
        case 139: x_QEvent::x_139(args);	break;
        case 140: x_QEvent::x_140(args);	break;
        case 141: x_QEvent::x_141(args);	break;
        case 142: x_QEvent::x_142(args);	break;
        case 143: x_QEvent::x_143(args);	break;
        case 144: x_QEvent::x_144(args);	break;
        case 145: x_QEvent::x_145(args);	break;
        case 146: x_QEvent::x_146(args);	break;
        case 147: x_QEvent::x_147(args);	break;
        case 148: x_QEvent::x_148(args);	break;
        case 149: x_QEvent::x_149(args);	break;
        case 150: x_QEvent::x_150(args);	break;
        case 151: x_QEvent::x_151(args);	break;
        case 152: x_QEvent::x_152(args);	break;
        case 153: x_QEvent::x_153(args);	break;
        case 154: x_QEvent::x_154(args);	break;
        case 155: x_QEvent::x_155(args);	break;
        case 156: x_QEvent::x_156(args);	break;
        case 157: x_QEvent::x_157(args);	break;
        case 158: x_QEvent::x_158(args);	break;
        case 159: x_QEvent::x_159(args);	break;
        case 160: x_QEvent::x_160(args);	break;
        case 161: x_QEvent::x_161(args);	break;
        case 162: x_QEvent::x_162(args);	break;
        case 163: x_QEvent::x_163(args);	break;
        case 164: x_QEvent::x_164(args);	break;
        case 165: x_QEvent::x_165(args);	break;
        case 166: x_QEvent::x_166(args);	break;
        case 167: x_QEvent::x_167(args);	break;
        case 168: x_QEvent::x_168(args);	break;
        case 169: x_QEvent::x_169(args);	break;
        case 170: x_QEvent::x_170(args);	break;
        case 171: x_QEvent::x_171(args);	break;
        case 172: x_QEvent::x_172(args);	break;
        case 173: x_QEvent::x_173(args);	break;
        case 174: x_QEvent::x_174(args);	break;
        case 175: x_QEvent::x_175(args);	break;
        case 176: delete (QEvent*)xself;	break;
    }
}
class x_QEventLoop : public QEventLoop, public __internal_SmokeClass {
    SmokeBinding* _binding;
public:
    void x_0(Smoke::Stack x) {
        // set the smoke binding
        _binding = (SmokeBinding*)x[1].s_class;
    }
    void x_1(Smoke::Stack x) {
        // virtual const QMetaObject* metaObject() const
        if (dynamic_cast<__internal_SmokeClass*>(static_cast<QEventLoop*>(this))) {
            const QMetaObject* xret = ((const x_QEventLoop*)this)->QEventLoop::metaObject();
            x[0].s_class = (void*)xret;
        } else {
            const QMetaObject* xret = ((const x_QEventLoop*)this)->metaObject();
            x[0].s_class = (void*)xret;
        }
    }
    void x_2(Smoke::Stack x) {
        // virtual void* qt_metacast(const char*)
        if (dynamic_cast<__internal_SmokeClass*>(static_cast<QEventLoop*>(this))) {
            void* xret = this->QEventLoop::qt_metacast((const char*)x[1].s_class);
            x[0].s_class = (void*)xret;
        } else {
            void* xret = this->qt_metacast((const char*)x[1].s_class);
            x[0].s_class = (void*)xret;
        }
    }
    static void x_3(Smoke::Stack x) {
        // static QString tr(const char*, const char*)
        QString xret = QEventLoop::tr((const char*)x[1].s_class,(const char*)x[2].s_class);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_4(Smoke::Stack x) {
        // static QString trUtf8(const char*, const char*)
        QString xret = QEventLoop::trUtf8((const char*)x[1].s_class,(const char*)x[2].s_class);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_5(Smoke::Stack x) {
        // static QString tr(const char*, const char*, int)
        QString xret = QEventLoop::tr((const char*)x[1].s_class,(const char*)x[2].s_class,(int)x[3].s_int);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_6(Smoke::Stack x) {
        // static QString trUtf8(const char*, const char*, int)
        QString xret = QEventLoop::trUtf8((const char*)x[1].s_class,(const char*)x[2].s_class,(int)x[3].s_int);
        x[0].s_class = (void*)new QString(xret);
    }
    void x_7(Smoke::Stack x) {
        // virtual int qt_metacall(QMetaObject::Call, int, void**)
        if (dynamic_cast<__internal_SmokeClass*>(static_cast<QEventLoop*>(this))) {
            int xret = this->QEventLoop::qt_metacall((QMetaObject::Call)x[1].s_enum,(int)x[2].s_int,(void**)x[3].s_class);
            x[0].s_int = xret;
        } else {
            int xret = this->qt_metacall((QMetaObject::Call)x[1].s_enum,(int)x[2].s_int,(void**)x[3].s_class);
            x[0].s_int = xret;
        }
    }
    static void x_8(Smoke::Stack x) {
        // QEventLoop* QEventLoop(QObject*)
        x_QEventLoop* xret = new x_QEventLoop((QObject*)x[1].s_class);
        x[0].s_class = (void*)xret;
    }
    explicit x_QEventLoop(QObject* x1) : QEventLoop(x1) {}
    void x_9(Smoke::Stack x) {
        // bool processEvents(QFlags<QEventLoop::ProcessEventsFlag>)
        bool xret = this->QEventLoop::processEvents((QFlags<QEventLoop::ProcessEventsFlag>)x[1].s_uint);
        x[0].s_bool = xret;
    }
    void x_10(Smoke::Stack x) {
        // void processEvents(QFlags<QEventLoop::ProcessEventsFlag>, int)
        this->QEventLoop::processEvents((QFlags<QEventLoop::ProcessEventsFlag>)x[1].s_uint,(int)x[2].s_int);
        (void)x; // noop (for compiler warning)
    }
    void x_11(Smoke::Stack x) {
        // int exec(QFlags<QEventLoop::ProcessEventsFlag>)
        int xret = this->QEventLoop::exec((QFlags<QEventLoop::ProcessEventsFlag>)x[1].s_uint);
        x[0].s_int = xret;
    }
    void x_12(Smoke::Stack x) {
        // void exit(int)
        this->QEventLoop::exit((int)x[1].s_int);
        (void)x; // noop (for compiler warning)
    }
    void x_13(Smoke::Stack x) {
        // bool isRunning() const
        bool xret = ((const x_QEventLoop*)this)->QEventLoop::isRunning();
        x[0].s_bool = xret;
    }
    void x_14(Smoke::Stack x) {
        // void wakeUp()
        this->QEventLoop::wakeUp();
        (void)x; // noop (for compiler warning)
    }
    void x_15(Smoke::Stack x) {
        // void quit()
        this->QEventLoop::quit();
        (void)x; // noop (for compiler warning)
    }
    static void x_16(Smoke::Stack x) {
        // static QString tr(const char*)
        QString xret = QEventLoop::tr((const char*)x[1].s_class,(const char*)0);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_17(Smoke::Stack x) {
        // static QString trUtf8(const char*)
        QString xret = QEventLoop::trUtf8((const char*)x[1].s_class,(const char*)0);
        x[0].s_class = (void*)new QString(xret);
    }
    static void x_18(Smoke::Stack x) {
        // QEventLoop* QEventLoop()
        x_QEventLoop* xret = new x_QEventLoop((QObject*)0);
        x[0].s_class = (void*)xret;
    }
    void x_19(Smoke::Stack x) {
        // bool processEvents()
        bool xret = this->QEventLoop::processEvents((QFlags<QEventLoop::ProcessEventsFlag>)QEventLoop::AllEvents);
        x[0].s_bool = xret;
    }
    void x_20(Smoke::Stack x) {
        // int exec()
        int xret = this->QEventLoop::exec((QFlags<QEventLoop::ProcessEventsFlag>)QEventLoop::AllEvents);
        x[0].s_int = xret;
    }
    void x_21(Smoke::Stack x) {
        // void exit()
        this->QEventLoop::exit((int)0);
        (void)x; // noop (for compiler warning)
    }
    static void x_22(Smoke::Stack x) {
        // static const QMetaObject staticMetaObject
        x[0].s_class = (void*)&QEventLoop::staticMetaObject;
    }
    static void x_23(Smoke::Stack x) {
        x[0].s_enum = (long)QEventLoop::AllEvents;
    }
    static void x_24(Smoke::Stack x) {
        x[0].s_enum = (long)QEventLoop::ExcludeUserInputEvents;
    }
    static void x_25(Smoke::Stack x) {
        x[0].s_enum = (long)QEventLoop::ExcludeSocketNotifiers;
    }
    static void x_26(Smoke::Stack x) {
        x[0].s_enum = (long)QEventLoop::WaitForMoreEvents;
    }
    static void x_27(Smoke::Stack x) {
        x[0].s_enum = (long)QEventLoop::X11ExcludeTimers;
    }
    static void x_28(Smoke::Stack x) {
        x[0].s_enum = (long)QEventLoop::DeferredDeletion;
    }
    static void x_29(Smoke::Stack x) {
        x[0].s_enum = (long)QEventLoop::EventLoopExec;
    }
    static void x_30(Smoke::Stack x) {
        x[0].s_enum = (long)QEventLoop::DialogExec;
    }
    virtual const QMetaObject* metaObject() const {
        Smoke::StackItem x[1];
        if (this->_binding->callMethod(1661, (void*)this, x)) return (const QMetaObject*)x[0].s_class;
        return this->QEventLoop::metaObject();
    }
    virtual void* qt_metacast(const char* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(1662, (void*)this, x)) return (void*)x[0].s_class;
        return this->QEventLoop::qt_metacast(x1);
    }
    virtual int qt_metacall(QMetaObject::Call x1, int x2, void** x3) {
        Smoke::StackItem x[4];
        x[1].s_enum = x1;
        x[2].s_int = x2;
        x[3].s_class = (void*)x3;
        if (this->_binding->callMethod(1667, (void*)this, x)) return (int)x[0].s_int;
        return this->QEventLoop::qt_metacall(x1, x2, x3);
    }
    virtual bool event(QEvent* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(3804, (void*)this, x)) return (bool)x[0].s_bool;
        return this->QObject::event(x1);
    }
    virtual bool eventFilter(QObject* x1, QEvent* x2) {
        Smoke::StackItem x[3];
        x[1].s_class = (void*)x1;
        x[2].s_class = (void*)x2;
        if (this->_binding->callMethod(3805, (void*)this, x)) return (bool)x[0].s_bool;
        return this->QObject::eventFilter(x1, x2);
    }
    virtual void timerEvent(QTimerEvent* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(3841, (void*)this, x)) return;
        this->QObject::timerEvent(x1);
    }
    virtual void childEvent(QChildEvent* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(3842, (void*)this, x)) return;
        this->QObject::childEvent(x1);
    }
    virtual void customEvent(QEvent* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(3843, (void*)this, x)) return;
        this->QObject::customEvent(x1);
    }
    virtual void connectNotify(const char* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(3844, (void*)this, x)) return;
        this->QObject::connectNotify(x1);
    }
    virtual void disconnectNotify(const char* x1) {
        Smoke::StackItem x[2];
        x[1].s_class = (void*)x1;
        if (this->_binding->callMethod(3845, (void*)this, x)) return;
        this->QObject::disconnectNotify(x1);
    }
    static void xenum_operation(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
        switch(xtype) {
        case 100: //QEventLoop::ProcessEventsFlag
            switch(xop) {
                case Smoke::EnumNew:
                    xdata = (void*)new QEventLoop::ProcessEventsFlag;
                    break;
                case Smoke::EnumDelete:
                    delete (QEventLoop::ProcessEventsFlag*)xdata;
                    break;
                case Smoke::EnumFromLong:
                    *(QEventLoop::ProcessEventsFlag*)xdata = (QEventLoop::ProcessEventsFlag)xvalue;
                    break;
                case Smoke::EnumToLong:
                    xvalue = (long)*(QEventLoop::ProcessEventsFlag*)xdata;
                    break;
            }
            break;
        }
    }
    ~x_QEventLoop() { this->_binding->deleted(42, (void*)this); }
};
void xenum_QEventLoop(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {
    x_QEventLoop::xenum_operation(xop, xtype, xdata, xvalue);
}
void xcall_QEventLoop(Smoke::Index xi, void *obj, Smoke::Stack args) {
    x_QEventLoop *xself = (x_QEventLoop*)obj;
    switch(xi) {
        case 0: xself->x_0(args);	break;
        case 1: xself->x_1(args);	break;
        case 2: xself->x_2(args);	break;
        case 3: x_QEventLoop::x_3(args);	break;
        case 4: x_QEventLoop::x_4(args);	break;
        case 5: x_QEventLoop::x_5(args);	break;
        case 6: x_QEventLoop::x_6(args);	break;
        case 7: xself->x_7(args);	break;
        case 8: x_QEventLoop::x_8(args);	break;
        case 9: xself->x_9(args);	break;
        case 10: xself->x_10(args);	break;
        case 11: xself->x_11(args);	break;
        case 12: xself->x_12(args);	break;
        case 13: xself->x_13(args);	break;
        case 14: xself->x_14(args);	break;
        case 15: xself->x_15(args);	break;
        case 16: x_QEventLoop::x_16(args);	break;
        case 17: x_QEventLoop::x_17(args);	break;
        case 18: x_QEventLoop::x_18(args);	break;
        case 19: xself->x_19(args);	break;
        case 20: xself->x_20(args);	break;
        case 21: xself->x_21(args);	break;
        case 22: x_QEventLoop::x_22(args);	break;
        case 23: x_QEventLoop::x_23(args);	break;
        case 24: x_QEventLoop::x_24(args);	break;
        case 25: x_QEventLoop::x_25(args);	break;
        case 26: x_QEventLoop::x_26(args);	break;
        case 27: x_QEventLoop::x_27(args);	break;
        case 28: x_QEventLoop::x_28(args);	break;
        case 29: x_QEventLoop::x_29(args);	break;
        case 30: x_QEventLoop::x_30(args);	break;
        case 31: delete (QEventLoop*)xself;	break;
    }
}

}
